-- NEXORA ERP Pass 18 - CRM, Documents, Notifications, Portals, PWA and Advanced Operations
-- Public endpoints are limited to the locked source catalog. Portal/PWA policy
-- tables support already-locked portal/technician routes without inventing new APIs.

CREATE TABLE "Lead" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "leadNo" VARCHAR(160) NOT NULL, "source" VARCHAR(120), "companyName" VARCHAR(240) NOT NULL, "contactName" VARCHAR(160) NOT NULL, "phone" VARCHAR(60), "email" VARCHAR(320), "requirement" TEXT, "estimatedValue" DECIMAL(18,2), "expectedCloseDate" DATE, "status" VARCHAR(40) NOT NULL DEFAULT 'NEW', "disqualifiedReason" TEXT, "convertedOpportunityId" UUID, "createdById" UUID NOT NULL, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Lead_org_no_key" UNIQUE("organizationId","leadNo"), CONSTRAINT "Lead_status_check" CHECK ("status" IN ('NEW','CONTACTED','QUALIFIED','DISQUALIFIED','CONVERTED')));
CREATE TABLE "Opportunity" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "opportunityNo" VARCHAR(160) NOT NULL, "leadId" UUID, "customerId" UUID, "name" VARCHAR(240) NOT NULL, "stage" VARCHAR(80) NOT NULL, "probabilityPct" INTEGER NOT NULL DEFAULT 10, "estimatedValue" DECIMAL(18,2) NOT NULL DEFAULT 0, "expectedCloseDate" DATE, "status" VARCHAR(40) NOT NULL DEFAULT 'OPEN', "createdById" UUID NOT NULL, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Opportunity_org_no_key" UNIQUE("organizationId","opportunityNo"), CONSTRAINT "Opportunity_prob_check" CHECK ("probabilityPct" BETWEEN 0 AND 100), CONSTRAINT "Opportunity_status_check" CHECK ("status" IN ('OPEN','WON','LOST','ON_HOLD')));
CREATE TABLE "SiteSurvey" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "surveyNo" VARCHAR(160) NOT NULL, "opportunityId" UUID, "customerId" UUID NOT NULL, "siteId" UUID NOT NULL, "scheduledAt" TIMESTAMPTZ(6), "findings" TEXT, "estimatedEffortHours" DECIMAL(18,2), "status" VARCHAR(40) NOT NULL DEFAULT 'PLANNED', "createdById" UUID NOT NULL, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SiteSurvey_org_no_key" UNIQUE("organizationId","surveyNo"), CONSTRAINT "SiteSurvey_status_check" CHECK ("status" IN ('PLANNED','IN_PROGRESS','COMPLETED','CANCELLED')));
CREATE TABLE "Quotation" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "quotationNo" VARCHAR(160) NOT NULL, "opportunityId" UUID, "customerId" UUID NOT NULL, "siteId" UUID, "validUntil" DATE NOT NULL, "currency" VARCHAR(12) NOT NULL DEFAULT 'PKR', "subtotal" DECIMAL(18,2) NOT NULL, "taxTotal" DECIMAL(18,2) NOT NULL DEFAULT 0, "total" DECIMAL(18,2) NOT NULL, "terms" TEXT, "status" VARCHAR(40) NOT NULL DEFAULT 'DRAFT', "sentAt" TIMESTAMPTZ(6), "acceptedAt" TIMESTAMPTZ(6), "acceptedByName" VARCHAR(160), "createdById" UUID NOT NULL, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Quotation_org_no_key" UNIQUE("organizationId","quotationNo"), CONSTRAINT "Quotation_status_check" CHECK ("status" IN ('DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED','CANCELLED')));
CREATE TABLE "QuotationItem" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "quotationId" UUID NOT NULL, "productId" UUID, "description" VARCHAR(500) NOT NULL, "quantity" DECIMAL(18,4) NOT NULL, "unitPrice" DECIMAL(18,2) NOT NULL, "lineTotal" DECIMAL(18,2) NOT NULL, "taxCodeId" UUID, CONSTRAINT "QuotationItem_qty_check" CHECK ("quantity" > 0), CONSTRAINT "QuotationItem_price_check" CHECK ("unitPrice" >= 0));
CREATE TABLE "CustomerContract" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "contractNo" VARCHAR(160) NOT NULL, "customerId" UUID NOT NULL, "siteId" UUID, "quotationId" UUID, "title" VARCHAR(240) NOT NULL, "startDate" DATE NOT NULL, "endDate" DATE, "billingCycle" VARCHAR(40) NOT NULL, "amount" DECIMAL(18,2) NOT NULL DEFAULT 0, "terms" TEXT, "status" VARCHAR(40) NOT NULL DEFAULT 'DRAFT', "activatedAt" TIMESTAMPTZ(6), "createdById" UUID NOT NULL, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "CustomerContract_org_no_key" UNIQUE("organizationId","contractNo"), CONSTRAINT "CustomerContract_dates_check" CHECK ("endDate" IS NULL OR "endDate" >= "startDate"), CONSTRAINT "CustomerContract_status_check" CHECK ("status" IN ('DRAFT','ACTIVE','SUSPENDED','EXPIRED','TERMINATED')));
CREATE TABLE "CustomerContractItem" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "contractId" UUID NOT NULL, "description" VARCHAR(500) NOT NULL, "quantity" DECIMAL(18,4) NOT NULL DEFAULT 1, "unitPrice" DECIMAL(18,2) NOT NULL DEFAULT 0, "lineTotal" DECIMAL(18,2) NOT NULL DEFAULT 0);
CREATE TABLE "Document" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "subjectType" VARCHAR(120) NOT NULL, "subjectId" UUID, "title" VARCHAR(240) NOT NULL, "category" VARCHAR(80) NOT NULL, "currentVersionId" UUID, "retentionUntil" DATE, "status" VARCHAR(40) NOT NULL DEFAULT 'ACTIVE', "createdById" UUID NOT NULL, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Document_status_check" CHECK ("status" IN ('ACTIVE','DELETED','RETAINED')));
CREATE TABLE "DocumentVersion" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "documentId" UUID NOT NULL, "versionNo" INTEGER NOT NULL, "fileName" VARCHAR(260) NOT NULL, "mimeType" VARCHAR(160) NOT NULL, "sizeBytes" INTEGER NOT NULL, "checksumSha256" VARCHAR(128) NOT NULL, "objectKey" VARCHAR(500) NOT NULL, "uploadedById" UUID NOT NULL, "uploadedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DocumentVersion_org_doc_version_key" UNIQUE("organizationId","documentId","versionNo"), CONSTRAINT "DocumentVersion_size_check" CHECK ("sizeBytes" > 0));
CREATE TABLE "DocumentAccessLog" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "documentId" UUID NOT NULL, "actorUserId" UUID NOT NULL, "action" VARCHAR(60) NOT NULL, "ip" VARCHAR(64), "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Notification" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "userId" UUID NOT NULL, "title" VARCHAR(240) NOT NULL, "body" TEXT NOT NULL, "subjectType" VARCHAR(120), "subjectId" UUID, "severity" VARCHAR(40) NOT NULL DEFAULT 'INFO', "readAt" TIMESTAMPTZ(6), "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "NotificationPreference" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "userId" UUID NOT NULL, "channel" VARCHAR(40) NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "NotificationPreference_org_user_channel_key" UNIQUE("organizationId","userId","channel"));
CREATE TABLE "PortalAccount" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "userId" UUID NOT NULL, "portalType" VARCHAR(40) NOT NULL, "linkedSubjectType" VARCHAR(80) NOT NULL, "linkedSubjectId" UUID NOT NULL, "status" VARCHAR(40) NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PortalAccount_org_user_type_key" UNIQUE("organizationId","userId","portalType"));
CREATE TABLE "PortalAccessGrant" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "portalAccountId" UUID NOT NULL, "resourceType" VARCHAR(120) NOT NULL, "resourceId" UUID, "permission" VARCHAR(120) NOT NULL, "expiresAt" TIMESTAMPTZ(6), "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "PortalActivityLog" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "portalAccountId" UUID, "action" VARCHAR(120) NOT NULL, "subjectType" VARCHAR(120), "subjectId" UUID, "ip" VARCHAR(64), "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "OfflinePwaSyncPolicy" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL UNIQUE, "offlineEnabled" BOOLEAN NOT NULL DEFAULT false, "maxOfflineHours" INTEGER NOT NULL DEFAULT 0, "photoRequired" BOOLEAN NOT NULL DEFAULT false, "signatureRequired" BOOLEAN NOT NULL DEFAULT false, "updatedById" UUID, "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "OfflinePwaSyncPolicy_hours_check" CHECK ("maxOfflineHours" BETWEEN 0 AND 168));
CREATE TABLE "OfflinePwaSyncBatch" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "technicianUserId" UUID NOT NULL, "deviceId" VARCHAR(160) NOT NULL, "status" VARCHAR(40) NOT NULL DEFAULT 'RECEIVED', "receivedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "processedAt" TIMESTAMPTZ(6));
CREATE TABLE "OfflinePwaSyncItem" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "batchId" UUID NOT NULL, "entityType" VARCHAR(120) NOT NULL, "entityId" UUID, "action" VARCHAR(80) NOT NULL, "payloadJson" JSONB NOT NULL, "status" VARCHAR(40) NOT NULL DEFAULT 'PENDING', "errorMessage" TEXT, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "FleetVehicle" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "branchId" UUID, "vehicleNo" VARCHAR(120) NOT NULL, "registrationNo" VARCHAR(120) NOT NULL, "status" VARCHAR(40) NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "FleetVehicle_org_no_key" UNIQUE("organizationId","vehicleNo"));
CREATE TABLE "ToolAsset" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "branchId" UUID, "toolNo" VARCHAR(120) NOT NULL, "name" VARCHAR(240) NOT NULL, "status" VARCHAR(40) NOT NULL DEFAULT 'AVAILABLE', CONSTRAINT "ToolAsset_org_no_key" UNIQUE("organizationId","toolNo"));
CREATE TABLE "SafetyIncident" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "branchId" UUID, "subjectType" VARCHAR(120), "subjectId" UUID, "severity" VARCHAR(40) NOT NULL, "description" TEXT NOT NULL, "status" VARCHAR(40) NOT NULL DEFAULT 'OPEN', "reportedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "InspectionRun" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "subjectType" VARCHAR(120) NOT NULL, "subjectId" UUID NOT NULL, "result" VARCHAR(40) NOT NULL, "notes" TEXT, "inspectedById" UUID NOT NULL, "inspectedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "LocalizationString" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID, "locale" VARCHAR(20) NOT NULL, "namespace" VARCHAR(120) NOT NULL, "key" VARCHAR(240) NOT NULL, "value" TEXT NOT NULL, "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "LocalizationString_scope_key" UNIQUE("organizationId","locale","namespace","key"));

CREATE INDEX "Lead_org_status_created_idx" ON "Lead"("organizationId","status","createdAt");
CREATE INDEX "Opportunity_org_customer_status_idx" ON "Opportunity"("organizationId","customerId","status");
CREATE INDEX "SiteSurvey_org_customer_site_status_idx" ON "SiteSurvey"("organizationId","customerId","siteId","status");
CREATE INDEX "Quotation_org_customer_status_idx" ON "Quotation"("organizationId","customerId","status");
CREATE INDEX "CustomerContract_org_customer_status_idx" ON "CustomerContract"("organizationId","customerId","status");
CREATE INDEX "Document_org_subject_idx" ON "Document"("organizationId","subjectType","subjectId");
CREATE INDEX "Notification_org_user_read_created_idx" ON "Notification"("organizationId","userId","readAt","createdAt");
CREATE INDEX "PortalAccessGrant_org_account_resource_idx" ON "PortalAccessGrant"("organizationId","portalAccountId","resourceType");
CREATE INDEX "OfflinePwaSyncItem_org_batch_status_idx" ON "OfflinePwaSyncItem"("organizationId","batchId","status");
