export const C10_FINANCE_CORE = 'C10_FINANCE_CORE' as const;

export const FinanceCoreWorkflowStages = [
  'CUSTOMER_INVOICE_DRAFT_TO_APPROVED_TO_POSTED_TO_SENT_OR_CANCELLED',
  'SUPPLIER_INVOICE_THREE_WAY_MATCH_PO_GRN_INVOICE_BEFORE_APPROVAL',
  'SUPPLIER_INVOICE_MATCH_STATUS_SEPARATE_FROM_CANONICAL_INVOICE_STATUS',
  'PAYMENT_IDEMPOTENCY_ALLOCATIONS_ONE_FINANCIAL_EFFECT',
  'DOUBLE_ENTRY_JOURNAL_BALANCED_AND_POSTED_IN_TRANSACTION',
  'AR_AP_AGING_PERMISSION_SCOPED',
  'EXPENSE_APPROVAL_FINANCE_VERIFICATION_AND_PAYMENT_HANDOFF',
  'REVERSAL_NOT_DESTRUCTIVE_LEDGER_EDIT',
] as const;

export const FinanceCoreCommandEndpoints = [
  'POST /api/v1/customer-invoices/:id/submit',
  'POST /api/v1/customer-invoices/:id/approve',
  'POST /api/v1/customer-invoices/:id/post',
  'POST /api/v1/customer-invoices/:id/send',
  'POST /api/v1/customer-invoices/:id/cancel',
  'POST /api/v1/supplier-invoices/:id/match',
  'POST /api/v1/supplier-invoices/:id/approve',
  'POST /api/v1/payments',
  'POST /api/v1/journal-entries/:id/post',
] as const;

export const FinanceCoreAtomicTransactionRules = [
  'CUSTOMER_INVOICE_POST_CREATES_JOURNAL_AND_STATUS_IN_ONE_TRANSACTION',
  'SUPPLIER_INVOICE_THREE_WAY_MATCH_UPDATES_MATCH_STATUS_WITH_AUDIT_IN_ONE_TRANSACTION',
  'PAYMENT_POST_ALLOCATES_BALANCES_CREATES_PAYMENT_AND_JOURNAL_ONCE_PER_IDEMPOTENCY_KEY',
  'EXPENSE_SUBMIT_APPROVAL_AND_FINANCE_VERIFICATION_ARE_STATE_MACHINE_COMMANDS',
  'POSTED_JOURNAL_AND_LEDGER_EFFECTS_ARE_REVERSED_NOT_DESTRUCTIVELY_EDITED',
  'FINANCE_CRITICAL_MUTATIONS_NEVER_RUN_AS_BULLMQ_SIDE_EFFECTS',
] as const;

export const FinanceCoreAcceptanceScenarios = [
  'C10-CUSTOMER-INVOICE-SUBMIT-APPROVE-POST-SEND-CANCEL-STATE-MACHINE',
  'C10-SUPPLIER-INVOICE-THREE-WAY-MATCH-PO-GRN-INVOICE',
  'C10-SUPPLIER-INVOICE-MATCH-STATUS-NOT-CANONICAL-INVOICE-STATUS',
  'C10-PAYMENT-IDEMPOTENCY-ONE-FINANCIAL-EFFECT',
  'C10-PAYMENT-PARTIAL-FULL-BALANCE-RECONCILIATION',
  'C10-JOURNAL-BALANCED-POSTING-AND-REVERSAL-ONLY-CORRECTION',
  'C10-AR-AP-AGING-TENANT-BRANCH-PERMISSION-SCOPE',
  'C10-EXPENSE-APPROVAL-FINANCE-VERIFICATION-PAYMENT-HANDOFF',
] as const;

export type FinanceCoreWorkflowStage = typeof FinanceCoreWorkflowStages[number];
export type FinanceCoreAcceptanceScenario = typeof FinanceCoreAcceptanceScenarios[number];
