export const CONTRACT_MATURITY = {
  EXPLICIT_SHARED_ZOD_SCHEMA: 'EXPLICIT_SHARED_ZOD_SCHEMA',
  SOURCE_EXAMPLE_BASELINE: 'SOURCE_EXAMPLE_BASELINE',
  ROUTE_SIGNATURE_ONLY: 'ROUTE_SIGNATURE_ONLY',
} as const;

export type ContractMaturity =
  (typeof CONTRACT_MATURITY)[keyof typeof CONTRACT_MATURITY];
