import { Prisma, withTransaction, type TransactionClient } from '@nexora/database';
import { AuditWriter } from '../../../core/audit/audit-writer.js';
import { BusinessEventWriter } from '../../../core/events/business-event-writer.js';
import { AppError } from '../../../core/http/errors.js';
import type { TenantRequestContext } from '../../../core/tenant/tenant-context.js';
import type { ApprovalFinalDecision } from '../../approvals/index.js';
import type { ApprovalFacade } from '../../approvals/index.js';
import type { PlatformAccessFacade } from '../../platform/configuration/index.js';
import { LeaveRepository } from './leave.repository.js';
const DEFAULT_PAGE_SIZE = 25;
const MAX_PAGE_SIZE = 100;
function paging(q: { page?: number; pageSize?: number }) { const page = q.page ?? 1; const pageSize = Math.min(q.pageSize ?? DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE); return { page, pageSize, skip: (page - 1) * pageSize, take: pageSize }; }
function day(value: string) { return new Date(`${value}T00:00:00.000Z`); }
function daysInclusive(from: string | Date, to: string | Date) { const start = from instanceof Date ? from : day(from); const end = to instanceof Date ? to : day(to); return Math.floor((end.getTime() - start.getTime()) / 86400000) + 1; }
export class LeaveService {
  constructor(private readonly approvals: ApprovalFacade, private readonly access: PlatformAccessFacade, private readonly repository = new LeaveRepository(), private readonly audit = new AuditWriter(), private readonly events = new BusinessEventWriter()) {}
  async list(tenant: TenantRequestContext, query: any) { await this.access.assertModuleEnabled(tenant.organizationId, 'hr'); const p = paging(query); const result = await this.repository.list({ organizationId: tenant.organizationId, branchScopeId: tenant.branchId, employeeId: query.employeeId, leaveTypeId: query.leaveTypeId, status: query.status, from: query.from ? day(query.from) : undefined, to: query.to ? day(query.to) : undefined, skip: p.skip, take: p.take }); return { ...p, rows: result.rows, total: result.total }; }
  async get(tenant: TenantRequestContext, id: string) { await this.access.assertModuleEnabled(tenant.organizationId, 'hr'); const row = await this.repository.get(tenant.organizationId, tenant.branchId, id); if (!row) throw new AppError(404, 'LEAVE_REQUEST_NOT_FOUND', 'Leave request not found.'); return row; }
  async create(tenant: TenantRequestContext, actor: { userId: string; ip: string | null }, input: any) {
    await this.access.assertModuleEnabled(tenant.organizationId, 'hr');
    const employee = await this.repository.getEmployee(tenant.organizationId, tenant.branchId, input.employeeId); if (!employee) throw new AppError(404, 'LEAVE_EMPLOYEE_NOT_FOUND', 'Employee not found in the active tenant scope.');
    const leaveType = await this.repository.getLeaveType(tenant.organizationId, input.leaveTypeId); if (!leaveType) throw new AppError(404, 'LEAVE_TYPE_NOT_FOUND', 'Leave type not found.');
    const days = new Prisma.Decimal(daysInclusive(input.fromDate, input.toDate));
    return withTransaction(async (tx) => { const row = await this.repository.create(tx, { organizationId: tenant.organizationId, employeeId: input.employeeId, leaveTypeId: input.leaveTypeId, fromDate: day(input.fromDate), toDate: day(input.toDate), days, reason: input.reason ?? null, status: 'DRAFT' }); await this.audit.append(tx, { organizationId: tenant.organizationId, actorUserId: actor.userId, action: 'LEAVE_REQUEST_CREATED', subjectType: 'LeaveRequest', subjectId: row.id, afterJson: { employeeId: row.employeeId, days: days.toString(), status: row.status }, ip: actor.ip }); return row; });
  }
  async submit(tenant: TenantRequestContext, actor: { userId: string; ip: string | null }, id: string) {
    await this.access.assertModuleEnabled(tenant.organizationId, 'hr');
    return withTransaction(async (tx) => { const row = await this.repository.lock(tx, tenant.organizationId, id); if (!row) throw new AppError(404, 'LEAVE_REQUEST_NOT_FOUND', 'Leave request not found.'); if (row.status !== 'DRAFT') throw new AppError(409, 'LEAVE_SUBMIT_INVALID_STATE', 'Only DRAFT leave requests can be submitted.'); const current = await this.repository.get(tenant.organizationId, tenant.branchId, id); if (!current) throw new AppError(404, 'LEAVE_REQUEST_NOT_FOUND', 'Leave request not found.'); const requestedById = current.employee.userId ?? actor.userId; const approval = await this.approvals.requestApprovalIfConfigured(tx, { organizationId: tenant.organizationId, branchId: current.employee.branchId, subjectType: 'LeaveRequest', subjectId: id, requestedById, context: { employeeId: row.employeeId, leaveTypeId: row.leaveTypeId, days: row.days.toString() } }); const status = approval ? 'APPROVAL_PENDING' : 'APPROVED'; const updated = await this.repository.update(tx, id, { status, approvalRequestId: approval?.id ?? null, submittedAt: new Date(), ...(approval ? {} : { decisionAt: new Date() }) }); if (!approval) await this.consumeBalance(tx, tenant.organizationId, row.employeeId, row.leaveTypeId, row.fromDate, row.days); await this.audit.append(tx, { organizationId: tenant.organizationId, actorUserId: actor.userId, action: 'LEAVE_REQUEST_SUBMITTED', subjectType: 'LeaveRequest', subjectId: id, afterJson: { status, approvalRequestId: approval?.id ?? null }, ip: actor.ip }); await this.events.append(tx, { organizationId: tenant.organizationId, type: 'leave_request.submitted', aggregateType: 'LeaveRequest', aggregateId: id, payload: { status } }); return updated; });
  }
  async cancel(tenant: TenantRequestContext, actor: { userId: string; ip: string | null }, id: string, comment: string | null) { await this.access.assertModuleEnabled(tenant.organizationId, 'hr'); return withTransaction(async (tx) => { const row = await this.repository.lock(tx, tenant.organizationId, id); if (!row) throw new AppError(404, 'LEAVE_REQUEST_NOT_FOUND', 'Leave request not found.'); if (!['DRAFT', 'SUBMITTED', 'APPROVAL_PENDING'].includes(row.status)) throw new AppError(409, 'LEAVE_CANCEL_INVALID_STATE', 'Approved/rejected/cancelled leave cannot be cancelled silently.'); const updated = await this.repository.update(tx, id, { status: 'CANCELLED', cancelledAt: new Date() }); await this.audit.append(tx, { organizationId: tenant.organizationId, actorUserId: actor.userId, action: 'LEAVE_REQUEST_CANCELLED', subjectType: 'LeaveRequest', subjectId: id, beforeJson: { status: row.status }, afterJson: { status: 'CANCELLED', comment }, ip: actor.ip }); return updated; }); }
  async applyApprovalDecision(tx: TransactionClient, input: { organizationId: string; subjectId: string; decision: ApprovalFinalDecision; actorUserId: string; comment: string | null; approvalRequestId: string }) { const row = await this.repository.lock(tx, input.organizationId, input.subjectId); if (!row) throw new AppError(404, 'LEAVE_REQUEST_NOT_FOUND', 'Leave request not found.'); if (row.status !== 'APPROVAL_PENDING') throw new AppError(409, 'LEAVE_APPROVAL_INVALID_STATE', 'Leave request is not awaiting approval.'); const status = input.decision === 'APPROVED' ? 'APPROVED' : 'REJECTED'; const updated = await this.repository.update(tx, input.subjectId, { status, decisionAt: new Date() }); if (status === 'APPROVED') await this.consumeBalance(tx, input.organizationId, row.employeeId, row.leaveTypeId, row.fromDate, row.days); await this.audit.append(tx, { organizationId: input.organizationId, actorUserId: input.actorUserId, action: 'LEAVE_APPROVAL_APPLIED', subjectType: 'LeaveRequest', subjectId: input.subjectId, afterJson: { status, approvalRequestId: input.approvalRequestId, comment: input.comment }, ip: null }); return updated; }
  private async consumeBalance(tx: TransactionClient, organizationId: string, employeeId: string, leaveTypeId: string, fromDate: Date, days: Prisma.Decimal) { const type = await this.repository.getLeaveType(organizationId, leaveTypeId); if (!type) throw new AppError(404, 'LEAVE_TYPE_NOT_FOUND', 'Leave type not found.'); const balance = await this.repository.lockBalance(tx, organizationId, employeeId, leaveTypeId, fromDate.getUTCFullYear(), type.annualAllowance); if (new Prisma.Decimal(balance.remaining).lt(days)) throw new AppError(409, 'LEAVE_BALANCE_INSUFFICIENT', 'Leave balance is insufficient.'); await this.repository.updateBalance(tx, balance.id, new Prisma.Decimal(balance.used).add(days), new Prisma.Decimal(balance.remaining).sub(days)); }
}
