import { z } from 'zod';
import { NonEmptyStringSchema, UuidSchema } from '../common';

export const C15_FRONTEND_WORKFLOW_COMPLETION = 'C15_FRONTEND_WORKFLOW_COMPLETION' as const;

export const FrontendWorkflowControlIds = [
  'C15-END-TO-END-LIFECYCLE-UI-COVERS-CUSTOMER-PROJECT-PROCUREMENT-STOCK-ASSET-FINANCE',
  'C15-FRONTEND-CALLS-API-ONLY-NO-BACKEND-DATABASE-IMPORTS',
  'C15-COMMAND-ENDPOINTS-USE-EXPLICIT-WORKFLOW-ACTIONS',
  'C15-IDEMPOTENCY-KEYS-FOR-GRN-PAYMENT-IMPORT-EXPORT-RETRY-SENSITIVE-COMMANDS',
  'C15-TANSTACK-QUERY-CACHING-INVALIDATION-AFTER-MUTATIONS',
  'C15-FORMS-USE-SHARED-ZOD-CONTRACTS-OR-MANIFESTED-PAYLOAD-SHAPES',
  'C15-WORKFLOW-STATE-GATES-BUTTONS-BY-STATUS-PERMISSIONS-AND-SCOPE',
  'C15-DESTRUCTIVE-HIGH-RISK-ACTIONS-REQUIRE-EXPLICIT-CONFIRMATION',
  'C15-DOCUMENTS-PHOTOS-SIGNATURES-USE-STORAGE-UPLOAD-INTENT',
  'C15-PORTAL-PWA-OFFLINE-SYNC-SURFACE-PRESENT',
  'C15-CRITICAL-STOCK-MONEY-APPROVAL-MUTATIONS-ARE-API-COMMANDS-NOT-FRONTEND-SHORTCUTS',
] as const;

export type FrontendWorkflowControlId = (typeof FrontendWorkflowControlIds)[number];

export const FrontendWorkflowStageSchema = z.enum([
  'CRM_AND_PROJECT_START',
  'PROJECT_BOM_AND_MATERIAL_REQUIREMENT',
  'PROCUREMENT_RFQ_PO_GRN',
  'INVENTORY_STOCK_SERIAL_BATCH',
  'ASSET_INSTALLATION_QR_WARRANTY',
  'FIELD_SERVICE_AND_MAINTENANCE',
  'FINANCE_MATCH_POST_PAY',
  'DOCUMENTS_REPORTS_PORTALS',
]);
export type FrontendWorkflowStage = z.infer<typeof FrontendWorkflowStageSchema>;

export const FrontendWorkflowHttpMethodSchema = z.enum(['GET', 'POST', 'PUT', 'PATCH', 'DELETE']);
export type FrontendWorkflowHttpMethod = z.infer<typeof FrontendWorkflowHttpMethodSchema>;

export const FrontendWorkflowCommandSchema = z.object({
  id: NonEmptyStringSchema,
  stage: FrontendWorkflowStageSchema,
  label: NonEmptyStringSchema,
  method: FrontendWorkflowHttpMethodSchema,
  endpointTemplate: NonEmptyStringSchema,
  requiredPermission: NonEmptyStringSchema,
  requiresIdempotencyKey: z.boolean().default(false),
  destructiveOrHighRisk: z.boolean().default(false),
  requiredStatus: z.array(NonEmptyStringSchema).default([]),
  invalidates: z.array(NonEmptyStringSchema).default([]),
  defaultPayload: z.record(z.string(), z.unknown()).default({}),
});
export type FrontendWorkflowCommand = z.infer<typeof FrontendWorkflowCommandSchema>;

export const FrontendWorkflowContextSchema = z.object({
  customerId: UuidSchema.optional(),
  vendorId: UuidSchema.optional(),
  projectId: UuidSchema.optional(),
  billOfMaterialsId: UuidSchema.optional(),
  purchaseRequestId: UuidSchema.optional(),
  rfqId: UuidSchema.optional(),
  supplierQuotationId: UuidSchema.optional(),
  purchaseOrderId: UuidSchema.optional(),
  goodsReceiptId: UuidSchema.optional(),
  supplierInvoiceId: UuidSchema.optional(),
  customerInvoiceId: UuidSchema.optional(),
  paymentId: UuidSchema.optional(),
  stockTransferId: UuidSchema.optional(),
  stockAdjustmentId: UuidSchema.optional(),
  assetId: UuidSchema.optional(),
  workOrderId: UuidSchema.optional(),
  maintenanceScheduleId: UuidSchema.optional(),
  importBatchId: UuidSchema.optional(),
  reportId: UuidSchema.optional(),
});
export type FrontendWorkflowContext = z.infer<typeof FrontendWorkflowContextSchema>;

export const FrontendWorkflowCommandCatalog: readonly FrontendWorkflowCommand[] = [
  {
    id: 'project-create-material-requirement',
    stage: 'PROJECT_BOM_AND_MATERIAL_REQUIREMENT',
    label: 'Create material requirement from project shortage',
    method: 'POST',
    endpointTemplate: '/projects/{projectId}/material-request',
    requiredPermission: 'project.update',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: false,
    requiredStatus: ['ACTIVE', 'PLANNED'],
    invalidates: ['projects', 'procurement', 'inventory'],
    defaultPayload: { reason: 'BOM shortage from workflow UI', items: [] },
  },
  {
    id: 'project-approve-bom',
    stage: 'PROJECT_BOM_AND_MATERIAL_REQUIREMENT',
    label: 'Approve project BOM',
    method: 'POST',
    endpointTemplate: '/projects/{projectId}/bom/{billOfMaterialsId}/approve',
    requiredPermission: 'project.approve',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['DRAFT'],
    invalidates: ['projects', 'inventory'],
    defaultPayload: { comment: 'BOM approved from workflow completion workbench.' },
  },
  {
    id: 'purchase-request-submit',
    stage: 'PROCUREMENT_RFQ_PO_GRN',
    label: 'Submit purchase request',
    method: 'POST',
    endpointTemplate: '/purchase-requests/{purchaseRequestId}/submit',
    requiredPermission: 'purchase_request.create',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: false,
    requiredStatus: ['DRAFT'],
    invalidates: ['purchase-requests', 'approvals'],
    defaultPayload: {},
  },
  {
    id: 'purchase-request-approve',
    stage: 'PROCUREMENT_RFQ_PO_GRN',
    label: 'Approve purchase request',
    method: 'POST',
    endpointTemplate: '/purchase-requests/{purchaseRequestId}/approve',
    requiredPermission: 'purchase_request.approve',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['SUBMITTED', 'UNDER_REVIEW'],
    invalidates: ['purchase-requests', 'approvals', 'rfqs'],
    defaultPayload: { comment: 'Budget verified and material is required.' },
  },
  {
    id: 'purchase-request-create-rfq',
    stage: 'PROCUREMENT_RFQ_PO_GRN',
    label: 'Create RFQ from approved PR',
    method: 'POST',
    endpointTemplate: '/purchase-requests/{purchaseRequestId}/create-rfq',
    requiredPermission: 'rfq.create',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: false,
    requiredStatus: ['APPROVED'],
    invalidates: ['purchase-requests', 'rfqs'],
    defaultPayload: { closesAt: '2026-10-15T12:00:00.000Z' },
  },
  {
    id: 'rfq-invite-vendors',
    stage: 'PROCUREMENT_RFQ_PO_GRN',
    label: 'Invite vendors to RFQ',
    method: 'POST',
    endpointTemplate: '/rfqs/{rfqId}/invite-vendors',
    requiredPermission: 'rfq.create',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: false,
    requiredStatus: ['DRAFT'],
    invalidates: ['rfqs', 'vendors'],
    defaultPayload: { vendorIds: [] },
  },
  {
    id: 'rfq-publish',
    stage: 'PROCUREMENT_RFQ_PO_GRN',
    label: 'Publish RFQ',
    method: 'POST',
    endpointTemplate: '/rfqs/{rfqId}/publish',
    requiredPermission: 'rfq.create',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: false,
    requiredStatus: ['DRAFT'],
    invalidates: ['rfqs', 'communications'],
    defaultPayload: {},
  },
  {
    id: 'supplier-quotation-select',
    stage: 'PROCUREMENT_RFQ_PO_GRN',
    label: 'Select supplier quotation',
    method: 'POST',
    endpointTemplate: '/supplier-quotations/{supplierQuotationId}/select',
    requiredPermission: 'supplier_quotation.select',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['SUBMITTED'],
    invalidates: ['rfqs', 'purchase-orders', 'approvals'],
    defaultPayload: { selectionReason: 'Best value based on deterministic comparison.' },
  },
  {
    id: 'purchase-order-submit',
    stage: 'PROCUREMENT_RFQ_PO_GRN',
    label: 'Submit purchase order for approval',
    method: 'POST',
    endpointTemplate: '/purchase-orders/{purchaseOrderId}/submit',
    requiredPermission: 'purchase_order.create',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['DRAFT'],
    invalidates: ['purchase-orders', 'approvals'],
    defaultPayload: {},
  },
  {
    id: 'purchase-order-approve',
    stage: 'PROCUREMENT_RFQ_PO_GRN',
    label: 'Approve purchase order',
    method: 'POST',
    endpointTemplate: '/purchase-orders/{purchaseOrderId}/approve',
    requiredPermission: 'purchase_order.approve',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['APPROVAL_PENDING'],
    invalidates: ['purchase-orders', 'approvals'],
    defaultPayload: { comment: 'Commercial and approval checks passed.' },
  },
  {
    id: 'purchase-order-send',
    stage: 'PROCUREMENT_RFQ_PO_GRN',
    label: 'Send purchase order to vendor',
    method: 'POST',
    endpointTemplate: '/purchase-orders/{purchaseOrderId}/send',
    requiredPermission: 'purchase_order.approve',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: false,
    requiredStatus: ['APPROVED'],
    invalidates: ['purchase-orders', 'communications'],
    defaultPayload: {},
  },
  {
    id: 'goods-receipt-create',
    stage: 'PROCUREMENT_RFQ_PO_GRN',
    label: 'Receive goods against PO',
    method: 'POST',
    endpointTemplate: '/goods-receipts',
    requiredPermission: 'goods_receipt.create',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['PO_APPROVED', 'PO_SENT', 'PO_PARTIALLY_RECEIVED'],
    invalidates: ['goods-receipts', 'inventory', 'purchase-orders'],
    defaultPayload: { purchaseOrderId: '{purchaseOrderId}', warehouseId: '', receivedAt: '2026-10-01T09:00:00.000Z', items: [] },
  },
  {
    id: 'goods-receipt-inspect',
    stage: 'PROCUREMENT_RFQ_PO_GRN',
    label: 'Record GRN quality inspection',
    method: 'POST',
    endpointTemplate: '/goods-receipts/{goodsReceiptId}/inspect',
    requiredPermission: 'goods_receipt.create',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['RECEIVED', 'INSPECTION_PENDING'],
    invalidates: ['goods-receipts', 'inventory'],
    defaultPayload: { result: 'ACCEPTED', notes: 'Inspected from workflow completion workbench.' },
  },
  {
    id: 'inventory-transfer-dispatch',
    stage: 'INVENTORY_STOCK_SERIAL_BATCH',
    label: 'Dispatch stock transfer',
    method: 'POST',
    endpointTemplate: '/inventory/transfers/{stockTransferId}/dispatch',
    requiredPermission: 'inventory.transfer',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['DRAFT'],
    invalidates: ['inventory', 'stock-ledger'],
    defaultPayload: {},
  },
  {
    id: 'inventory-adjustment-post',
    stage: 'INVENTORY_STOCK_SERIAL_BATCH',
    label: 'Post stock adjustment',
    method: 'POST',
    endpointTemplate: '/inventory/adjustments/{stockAdjustmentId}/post',
    requiredPermission: 'inventory.adjust',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['APPROVED'],
    invalidates: ['inventory', 'stock-ledger', 'approvals'],
    defaultPayload: {},
  },
  {
    id: 'asset-install',
    stage: 'ASSET_INSTALLATION_QR_WARRANTY',
    label: 'Install asset at customer site',
    method: 'POST',
    endpointTemplate: '/assets/{assetId}/install',
    requiredPermission: 'asset.install',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['ISSUED', 'INSTALLED'],
    invalidates: ['assets', 'inventory', 'projects'],
    defaultPayload: { siteId: '', areaId: '', projectId: '{projectId}', technicianId: '', installedAt: '2026-10-01T11:10:00.000Z', locationText: 'Building A - Floor 2 - Corridor' },
  },
  {
    id: 'asset-qr-rotate',
    stage: 'ASSET_INSTALLATION_QR_WARRANTY',
    label: 'Rotate asset QR token',
    method: 'POST',
    endpointTemplate: '/assets/{assetId}/qr/rotate',
    requiredPermission: 'asset.manage_qr',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['ACTIVE', 'INSTALLED'],
    invalidates: ['assets'],
    defaultPayload: { reason: 'QR rotation requested from workflow UI.' },
  },
  {
    id: 'work-order-assign',
    stage: 'FIELD_SERVICE_AND_MAINTENANCE',
    label: 'Assign technician to work order',
    method: 'POST',
    endpointTemplate: '/work-orders/{workOrderId}/assign',
    requiredPermission: 'workorder.assign',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: false,
    requiredStatus: ['NEW', 'VALIDATED'],
    invalidates: ['work-orders', 'tickets', 'notifications'],
    defaultPayload: { technicianId: '' },
  },
  {
    id: 'work-order-complete',
    stage: 'FIELD_SERVICE_AND_MAINTENANCE',
    label: 'Complete work order with service report',
    method: 'POST',
    endpointTemplate: '/work-orders/{workOrderId}/complete',
    requiredPermission: 'workorder.close',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['RESOLVED', 'CUSTOMER_CONFIRMATION'],
    invalidates: ['work-orders', 'assets', 'inventory', 'tickets'],
    defaultPayload: { serviceReportId: '', customerConfirmed: true },
  },
  {
    id: 'maintenance-generate-work-order',
    stage: 'FIELD_SERVICE_AND_MAINTENANCE',
    label: 'Generate work order from due maintenance',
    method: 'POST',
    endpointTemplate: '/maintenance/schedules/{maintenanceScheduleId}/generate-work-order',
    requiredPermission: 'maintenance.execute',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: false,
    requiredStatus: ['DUE'],
    invalidates: ['maintenance', 'work-orders'],
    defaultPayload: {},
  },
  {
    id: 'supplier-invoice-match',
    stage: 'FINANCE_MATCH_POST_PAY',
    label: 'Run supplier invoice three-way match',
    method: 'POST',
    endpointTemplate: '/supplier-invoices/{supplierInvoiceId}/match',
    requiredPermission: 'supplier_invoice.approve',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['DRAFT', 'APPROVAL_PENDING'],
    invalidates: ['supplier-invoices', 'purchase-orders', 'goods-receipts'],
    defaultPayload: {},
  },
  {
    id: 'customer-invoice-post',
    stage: 'FINANCE_MATCH_POST_PAY',
    label: 'Post customer invoice',
    method: 'POST',
    endpointTemplate: '/customer-invoices/{customerInvoiceId}/post',
    requiredPermission: 'invoice.post',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['APPROVED'],
    invalidates: ['customer-invoices', 'journal-entries', 'finance'],
    defaultPayload: {},
  },
  {
    id: 'payment-record',
    stage: 'FINANCE_MATCH_POST_PAY',
    label: 'Record invoice payment',
    method: 'POST',
    endpointTemplate: '/payments',
    requiredPermission: 'payment.create',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: true,
    requiredStatus: ['POSTED_INVOICE', 'APPROVED_SUPPLIER_INVOICE'],
    invalidates: ['payments', 'customer-invoices', 'supplier-invoices', 'finance'],
    defaultPayload: { direction: 'INBOUND', partyType: 'CUSTOMER', partyId: '', amount: '0.00', method: 'BANK_TRANSFER', paidAt: '2026-10-10T10:00:00.000Z', allocations: [] },
  },
  {
    id: 'data-import-validate',
    stage: 'DOCUMENTS_REPORTS_PORTALS',
    label: 'Validate import batch',
    method: 'POST',
    endpointTemplate: '/imports/{importBatchId}/validate',
    requiredPermission: 'import.manage',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: false,
    requiredStatus: ['UPLOADED'],
    invalidates: ['imports'],
    defaultPayload: { dryRun: true },
  },
  {
    id: 'report-export',
    stage: 'DOCUMENTS_REPORTS_PORTALS',
    label: 'Request report export',
    method: 'POST',
    endpointTemplate: '/reports/exports',
    requiredPermission: 'report.export',
    requiresIdempotencyKey: true,
    destructiveOrHighRisk: false,
    requiredStatus: ['READY'],
    invalidates: ['reports', 'documents'],
    defaultPayload: { reportId: '{reportId}', format: 'PDF', filters: {} },
  },
  {
    id: 'document-upload-intent',
    stage: 'DOCUMENTS_REPORTS_PORTALS',
    label: 'Request document upload intent',
    method: 'POST',
    endpointTemplate: '/documents/upload-intent',
    requiredPermission: 'document.create',
    requiresIdempotencyKey: false,
    destructiveOrHighRisk: false,
    requiredStatus: ['ANY'],
    invalidates: ['documents'],
    defaultPayload: { fileName: 'site-photo.jpg', mimeType: 'image/jpeg', size: 1000, subjectType: 'PROJECT', subjectId: '{projectId}', category: 'SITE_PHOTO' },
  },
];

export const FrontendWorkflowReadModels = [
  '/customers?page=1&pageSize=10',
  '/projects?page=1&pageSize=10',
  '/purchase-requests?page=1&pageSize=10',
  '/purchase-orders?page=1&pageSize=10',
  '/inventory/stock?page=1&pageSize=10',
  '/assets?page=1&pageSize=10',
  '/work-orders?page=1&pageSize=10',
  '/customer-invoices?page=1&pageSize=10',
  '/supplier-invoices?page=1&pageSize=10',
  '/reports?page=1&pageSize=10',
] as const;

export const FrontendWorkflowCompletionManifest = {
  pass: 'C15',
  name: 'Frontend Workflow Completion',
  controls: FrontendWorkflowControlIds,
  commandCatalog: FrontendWorkflowCommandCatalog,
  readModels: FrontendWorkflowReadModels,
  uiRule: 'Frontend workflow screens must use public /api/v1 endpoints only. They must never import backend, database or server-only packages.',
  transactionRule: 'Critical stock, money and approval state changes remain backend API commands. The frontend only submits validated commands and displays results.',
  idempotencyRule: 'Retry-sensitive commands carry Idempotency-Key, especially GRN, payment, import commit/rollback, report export and workflow submit/approve/post commands.',
  stateRule: 'Buttons/actions are gated by visible status, required permission, tenant/branch/resource scope and destructive/high-risk confirmation.',
  evidenceRule: 'Documents, photos and signatures use upload intent/complete-upload and centralized storage; they are never direct MinIO browser shortcuts without API authorization.',
} as const;
