import type { FastifyReply, FastifyRequest } from 'fastify';
import { AcceptQuotationSchema, ActivateCustomerContractSchema, CreateCustomerContractSchema, CreateLeadSchema, CreateOpportunitySchema, CreateQuotationSchema, CreateSiteSurveySchema, CrmListQuerySchema, QualifyLeadSchema, SendQuotationSchema, UpdateCustomerContractSchema, UpdateLeadSchema, UpdateOpportunitySchema, UpdateQuotationSchema, UpdateSiteSurveySchema } from '@nexora/shared';
import { dataEnvelope, listEnvelope } from '../../core/http/envelope.js';
import { AppError } from '../../core/http/errors.js';
import { CrmService } from './crm.service.js';
function ctx(r:FastifyRequest){if(!r.auth||!r.tenant)throw new AppError(500,'AUTH_PIPELINE_INVALID','Authorization pipeline was not initialized.');return{auth:r.auth,tenant:r.tenant};}
function actor(r:FastifyRequest){const {auth}=ctx(r);return{userId:auth.userId,ip:r.ip};}
function list(reply:FastifyReply, request:FastifyRequest, result:any){return reply.code(200).send(listEnvelope(result.rows,{page:result.page,pageSize:result.pageSize,total:result.total,requestId:request.id}));}
export class CrmController{constructor(private readonly service:CrmService){}
 listLeads=async(r:FastifyRequest,p:FastifyReply)=>list(p,r,await this.service.listLeads(ctx(r).tenant,CrmListQuerySchema.parse(r.query))); getLead=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.getLead(ctx(r).tenant,r.params.id),r.id)); createLead=async(r:FastifyRequest,p:FastifyReply)=>p.code(201).send(dataEnvelope(await this.service.createLead(ctx(r).tenant,actor(r),CreateLeadSchema.parse(r.body)),r.id)); updateLead=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.updateLead(ctx(r).tenant,actor(r),r.params.id,UpdateLeadSchema.parse(r.body)),r.id)); qualifyLead=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.qualifyLead(ctx(r).tenant,actor(r),r.params.id,QualifyLeadSchema.parse(r.body)),r.id));
 listOpportunities=async(r:FastifyRequest,p:FastifyReply)=>list(p,r,await this.service.listOpportunities(ctx(r).tenant,CrmListQuerySchema.parse(r.query))); getOpportunity=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.getOpportunity(ctx(r).tenant,r.params.id),r.id)); createOpportunity=async(r:FastifyRequest,p:FastifyReply)=>p.code(201).send(dataEnvelope(await this.service.createOpportunity(ctx(r).tenant,actor(r),CreateOpportunitySchema.parse(r.body)),r.id)); updateOpportunity=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.updateOpportunity(ctx(r).tenant,actor(r),r.params.id,UpdateOpportunitySchema.parse(r.body)),r.id));
 listSiteSurveys=async(r:FastifyRequest,p:FastifyReply)=>list(p,r,await this.service.listSiteSurveys(ctx(r).tenant,CrmListQuerySchema.parse(r.query))); getSiteSurvey=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.getSiteSurvey(ctx(r).tenant,r.params.id),r.id)); createSiteSurvey=async(r:FastifyRequest,p:FastifyReply)=>p.code(201).send(dataEnvelope(await this.service.createSiteSurvey(ctx(r).tenant,actor(r),CreateSiteSurveySchema.parse(r.body)),r.id)); updateSiteSurvey=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.updateSiteSurvey(ctx(r).tenant,actor(r),r.params.id,UpdateSiteSurveySchema.parse(r.body)),r.id));
 listQuotations=async(r:FastifyRequest,p:FastifyReply)=>list(p,r,await this.service.listQuotations(ctx(r).tenant,CrmListQuerySchema.parse(r.query))); getQuotation=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.getQuotation(ctx(r).tenant,r.params.id),r.id)); createQuotation=async(r:FastifyRequest,p:FastifyReply)=>p.code(201).send(dataEnvelope(await this.service.createQuotation(ctx(r).tenant,actor(r),CreateQuotationSchema.parse(r.body)),r.id)); updateQuotation=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.updateQuotation(ctx(r).tenant,actor(r),r.params.id,UpdateQuotationSchema.parse(r.body)),r.id)); sendQuotation=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.sendQuotation(ctx(r).tenant,actor(r),r.params.id,SendQuotationSchema.parse(r.body??{})),r.id)); acceptQuotation=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.acceptQuotation(ctx(r).tenant,actor(r),r.params.id,AcceptQuotationSchema.parse(r.body??{})),r.id));
 listContracts=async(r:FastifyRequest,p:FastifyReply)=>list(p,r,await this.service.listContracts(ctx(r).tenant,CrmListQuerySchema.parse(r.query))); getContract=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.getContract(ctx(r).tenant,r.params.id),r.id)); createContract=async(r:FastifyRequest,p:FastifyReply)=>p.code(201).send(dataEnvelope(await this.service.createContract(ctx(r).tenant,actor(r),CreateCustomerContractSchema.parse(r.body)),r.id)); updateContract=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.updateContract(ctx(r).tenant,actor(r),r.params.id,UpdateCustomerContractSchema.parse(r.body)),r.id)); activateContract=async(r:FastifyRequest<{Params:{id:string}}>,p:FastifyReply)=>p.code(200).send(dataEnvelope(await this.service.activateContract(ctx(r).tenant,actor(r),r.params.id,ActivateCustomerContractSchema.parse(r.body??{})),r.id));}
