import type { FastifyPluginAsync, FastifyRequest } from 'fastify';
import { defineLockedRoute } from '../../core/contracts/locked-route.js';
import type { IdentityFacade } from '../identity/index.js';
import type { PlatformAccessFacade } from '../platform/configuration/index.js';
import type { CrmController } from './crm.controller.js';
const defs={
 leads:defineLockedRoute('GET','/api/v1/leads'), lead:defineLockedRoute('GET','/api/v1/leads/:id'), createLead:defineLockedRoute('POST','/api/v1/leads'), updateLead:defineLockedRoute('PATCH','/api/v1/leads/:id'), qualifyLead:defineLockedRoute('POST','/api/v1/leads/:id/qualify'),
 opportunities:defineLockedRoute('GET','/api/v1/opportunities'), opportunity:defineLockedRoute('GET','/api/v1/opportunities/:id'), createOpportunity:defineLockedRoute('POST','/api/v1/opportunities'), updateOpportunity:defineLockedRoute('PATCH','/api/v1/opportunities/:id'),
 siteSurveys:defineLockedRoute('GET','/api/v1/site-surveys'), siteSurvey:defineLockedRoute('GET','/api/v1/site-surveys/:id'), createSiteSurvey:defineLockedRoute('POST','/api/v1/site-surveys'), updateSiteSurvey:defineLockedRoute('PATCH','/api/v1/site-surveys/:id'),
 quotations:defineLockedRoute('GET','/api/v1/quotations'), quotation:defineLockedRoute('GET','/api/v1/quotations/:id'), createQuotation:defineLockedRoute('POST','/api/v1/quotations'), updateQuotation:defineLockedRoute('PATCH','/api/v1/quotations/:id'), sendQuotation:defineLockedRoute('POST','/api/v1/quotations/:id/send'), acceptQuotation:defineLockedRoute('POST','/api/v1/quotations/:id/accept'),
 contracts:defineLockedRoute('GET','/api/v1/contracts'), contract:defineLockedRoute('GET','/api/v1/contracts/:id'), createContract:defineLockedRoute('POST','/api/v1/contracts'), updateContract:defineLockedRoute('PATCH','/api/v1/contracts/:id'), activateContract:defineLockedRoute('POST','/api/v1/contracts/:id/activate'),
} as const;
export function crmRoutes(controller:CrmController,identity:IdentityFacade,access:PlatformAccessFacade):FastifyPluginAsync{const guard=(permission:string)=>[identity.authenticateRequest.bind(identity),identity.resolveTenantRequest.bind(identity),async(request:FastifyRequest)=>{await access.assertModuleEnabled(request.tenant!.organizationId,'crm');await identity.assertPermission(request,permission);}];return async app=>{
 app.get(defs.leads.relativePath,{schema:defs.leads.schema,preHandler:guard('lead.view'),handler:controller.listLeads}); app.get(defs.lead.relativePath,{schema:defs.lead.schema,preHandler:guard('lead.view'),handler:controller.getLead}); app.post(defs.createLead.relativePath,{schema:defs.createLead.schema,preHandler:guard('lead.create'),handler:controller.createLead}); app.patch(defs.updateLead.relativePath,{schema:defs.updateLead.schema,preHandler:guard('lead.update'),handler:controller.updateLead}); app.post(defs.qualifyLead.relativePath,{schema:defs.qualifyLead.schema,preHandler:guard('lead.update'),handler:controller.qualifyLead});
 app.get(defs.opportunities.relativePath,{schema:defs.opportunities.schema,preHandler:guard('opportunity.view'),handler:controller.listOpportunities}); app.get(defs.opportunity.relativePath,{schema:defs.opportunity.schema,preHandler:guard('opportunity.view'),handler:controller.getOpportunity}); app.post(defs.createOpportunity.relativePath,{schema:defs.createOpportunity.schema,preHandler:guard('opportunity.create'),handler:controller.createOpportunity}); app.patch(defs.updateOpportunity.relativePath,{schema:defs.updateOpportunity.schema,preHandler:guard('opportunity.update'),handler:controller.updateOpportunity});
 app.get(defs.siteSurveys.relativePath,{schema:defs.siteSurveys.schema,preHandler:guard('site_survey.view'),handler:controller.listSiteSurveys}); app.get(defs.siteSurvey.relativePath,{schema:defs.siteSurvey.schema,preHandler:guard('site_survey.view'),handler:controller.getSiteSurvey}); app.post(defs.createSiteSurvey.relativePath,{schema:defs.createSiteSurvey.schema,preHandler:guard('site_survey.create'),handler:controller.createSiteSurvey}); app.patch(defs.updateSiteSurvey.relativePath,{schema:defs.updateSiteSurvey.schema,preHandler:guard('site_survey.update'),handler:controller.updateSiteSurvey});
 app.get(defs.quotations.relativePath,{schema:defs.quotations.schema,preHandler:guard('quotation.view'),handler:controller.listQuotations}); app.get(defs.quotation.relativePath,{schema:defs.quotation.schema,preHandler:guard('quotation.view'),handler:controller.getQuotation}); app.post(defs.createQuotation.relativePath,{schema:defs.createQuotation.schema,preHandler:guard('quotation.create'),handler:controller.createQuotation}); app.patch(defs.updateQuotation.relativePath,{schema:defs.updateQuotation.schema,preHandler:guard('quotation.update'),handler:controller.updateQuotation}); app.post(defs.sendQuotation.relativePath,{schema:defs.sendQuotation.schema,preHandler:guard('quotation.send'),handler:controller.sendQuotation}); app.post(defs.acceptQuotation.relativePath,{schema:defs.acceptQuotation.schema,preHandler:guard('quotation.approve'),handler:controller.acceptQuotation});
 app.get(defs.contracts.relativePath,{schema:defs.contracts.schema,preHandler:guard('contract.view'),handler:controller.listContracts}); app.get(defs.contract.relativePath,{schema:defs.contract.schema,preHandler:guard('contract.view'),handler:controller.getContract}); app.post(defs.createContract.relativePath,{schema:defs.createContract.schema,preHandler:guard('contract.create'),handler:controller.createContract}); app.patch(defs.updateContract.relativePath,{schema:defs.updateContract.schema,preHandler:guard('contract.update'),handler:controller.updateContract}); app.post(defs.activateContract.relativePath,{schema:defs.activateContract.schema,preHandler:guard('contract.activate'),handler:controller.activateContract});
};}
