import { Prisma, withTransaction } from '@nexora/database';
import { AuditWriter } from '../../core/audit/audit-writer.js';
import { BusinessEventWriter } from '../../core/events/business-event-writer.js';
import { AppError } from '../../core/http/errors.js';
import type { TenantRequestContext } from '../../core/tenant/tenant-context.js';
import type { CustomerFacade } from '../customers/index.js';
import type { NumberSequenceFacade } from '../platform/number-sequence/index.js';
import type { PlatformAccessFacade } from '../platform/configuration/index.js';
import { CrmRepository } from './crm.repository.js';
import { toCrmDto } from './crm.mapper.js';

function dec(v: any) { return new Prisma.Decimal(v ?? 0); }
function date(v?: string) { return v ? new Date(`${v}T00:00:00.000Z`) : null; }
function page(q: any) { const p = q.page ?? 1, pageSize = Math.min(q.pageSize ?? 25, 100); return { page: p, pageSize, skip: (p-1)*pageSize, take: pageSize }; }

export class CrmService {
  constructor(
    private readonly numbers: NumberSequenceFacade,
    private readonly customers: CustomerFacade,
    private readonly access: PlatformAccessFacade,
    private readonly repository = new CrmRepository(),
    private readonly audit = new AuditWriter(),
    private readonly events = new BusinessEventWriter(),
  ) {}
  private async enabled(organizationId: string) { await this.access.assertModuleEnabled(organizationId, 'crm'); }
  private async listModel(tenant: TenantRequestContext, model: any, query: any) { await this.enabled(tenant.organizationId); const p = page(query); const r = await this.repository.list(model, tenant.organizationId, query, p.skip, p.take); return { rows: r.rows.map(toCrmDto), total: r.total, page: p.page, pageSize: p.pageSize }; }
  private async getModel(tenant: TenantRequestContext, model: any, id: string, code: string) { await this.enabled(tenant.organizationId); const row = await this.repository.get(model, tenant.organizationId, id); if (!row) throw new AppError(404, code, 'Requested CRM record was not found.'); return toCrmDto(row); }

  listLeads(t: TenantRequestContext, q: any) { return this.listModel(t, 'lead', q); }
  getLead(t: TenantRequestContext, id: string) { return this.getModel(t, 'lead', id, 'LEAD_NOT_FOUND'); }
  createLead(t: TenantRequestContext, actor: any, input: any) {
    return this.numbers.withBusinessNumber({ organizationId: t.organizationId, branchId: t.branchId, entityType: 'LEAD', fiscalYear: new Date().getUTCFullYear(), targetType: 'Lead', createTarget: async (tx, leadNo) => {
      const row = await this.repository.withDb(tx).createLead({ organizationId: t.organizationId, leadNo, source: input.source ?? null, companyName: input.companyName, contactName: input.contactName, phone: input.phone ?? null, email: input.email ?? null, requirement: input.requirement ?? null, estimatedValue: input.estimatedValue ? dec(input.estimatedValue) : null, expectedCloseDate: date(input.expectedCloseDate), status: 'NEW', createdById: actor.userId });
      await this.audit.append(tx, { organizationId: t.organizationId, actorUserId: actor.userId, action: 'LEAD_CREATED', subjectType: 'Lead', subjectId: row.id, afterJson: toCrmDto(row), ip: actor.ip });
      return row;
    }});
  }
  async updateLead(t: TenantRequestContext, actor: any, id: string, input: any) { const before = await this.getLead(t, id); return withTransaction(async tx => { const row = await this.repository.withDb(tx).updateLead(id, { ...input, estimatedValue: input.estimatedValue ? dec(input.estimatedValue) : undefined, expectedCloseDate: input.expectedCloseDate ? date(input.expectedCloseDate) : undefined }); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'LEAD_UPDATED',subjectType:'Lead',subjectId:id,beforeJson:before,afterJson:toCrmDto(row),ip:actor.ip}); return toCrmDto(row); }); }
  async qualifyLead(t: TenantRequestContext, actor: any, id: string, input: any) { const lead = await this.getLead(t, id); return this.numbers.withBusinessNumber({ organizationId: t.organizationId, branchId: t.branchId, entityType: 'OPPORTUNITY', fiscalYear: new Date().getUTCFullYear(), targetType: 'Opportunity', createTarget: async (tx, opportunityNo) => { const repo = this.repository.withDb(tx); const opp = await repo.createOpportunity({ organizationId:t.organizationId, opportunityNo, leadId:id, customerId:input.customerId ?? null, name:input.opportunityName, stage:'QUALIFIED', probabilityPct:25, estimatedValue:dec(input.estimatedValue ?? lead.estimatedValue ?? 0), expectedCloseDate:date(input.expectedCloseDate), status:'OPEN', createdById:actor.userId }); await repo.updateLead(id,{status:'QUALIFIED',convertedOpportunityId:opp.id}); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'LEAD_QUALIFIED',subjectType:'Lead',subjectId:id,beforeJson:lead,afterJson:{opportunityId:opp.id},ip:actor.ip}); return opp; }}); }

  listOpportunities(t: TenantRequestContext, q: any) { return this.listModel(t, 'opportunity', q); }
  getOpportunity(t: TenantRequestContext, id: string) { return this.getModel(t, 'opportunity', id, 'OPPORTUNITY_NOT_FOUND'); }
  createOpportunity(t: TenantRequestContext, actor: any, input: any) { return this.numbers.withBusinessNumber({ organizationId:t.organizationId, branchId:t.branchId, entityType:'OPPORTUNITY', fiscalYear:new Date().getUTCFullYear(), targetType:'Opportunity', createTarget: async (tx, opportunityNo) => { const row = await this.repository.withDb(tx).createOpportunity({ organizationId:t.organizationId, opportunityNo, leadId:input.leadId??null, customerId:input.customerId??null, name:input.name, stage:input.stage, probabilityPct:input.probabilityPct, estimatedValue:dec(input.estimatedValue), expectedCloseDate:date(input.expectedCloseDate), status:'OPEN', createdById:actor.userId }); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'OPPORTUNITY_CREATED',subjectType:'Opportunity',subjectId:row.id,afterJson:toCrmDto(row),ip:actor.ip}); return row; }}); }
  async updateOpportunity(t: TenantRequestContext, actor: any, id: string, input: any) { const before = await this.getOpportunity(t,id); return withTransaction(async tx => { const row = await this.repository.withDb(tx).updateOpportunity(id,{...input,estimatedValue:input.estimatedValue?dec(input.estimatedValue):undefined,expectedCloseDate:input.expectedCloseDate?date(input.expectedCloseDate):undefined}); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'OPPORTUNITY_UPDATED',subjectType:'Opportunity',subjectId:id,beforeJson:before,afterJson:toCrmDto(row),ip:actor.ip}); return toCrmDto(row);}); }

  listSiteSurveys(t: TenantRequestContext, q: any) { return this.listModel(t, 'siteSurvey', q); }
  getSiteSurvey(t: TenantRequestContext, id: string) { return this.getModel(t, 'siteSurvey', id, 'SITE_SURVEY_NOT_FOUND'); }
  createSiteSurvey(t: TenantRequestContext, actor: any, input: any) { return this.numbers.withBusinessNumber({ organizationId:t.organizationId, branchId:t.branchId, entityType:'SITE_SURVEY', fiscalYear:new Date().getUTCFullYear(), targetType:'SiteSurvey', createTarget: async (tx, surveyNo) => { await this.customers.siteForProject(t.organizationId,input.customerId,input.siteId); const row=await this.repository.withDb(tx).createSiteSurvey({organizationId:t.organizationId,surveyNo,opportunityId:input.opportunityId??null,customerId:input.customerId,siteId:input.siteId,scheduledAt:input.scheduledAt?new Date(input.scheduledAt):null,findings:input.findings??null,estimatedEffortHours:input.estimatedEffortHours?dec(input.estimatedEffortHours):null,status:'PLANNED',createdById:actor.userId}); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'SITE_SURVEY_CREATED',subjectType:'SiteSurvey',subjectId:row.id,afterJson:toCrmDto(row),ip:actor.ip}); return row; }}); }
  async updateSiteSurvey(t: TenantRequestContext, actor: any, id: string, input: any) { const before=await this.getSiteSurvey(t,id); return withTransaction(async tx=>{ const row=await this.repository.withDb(tx).updateSiteSurvey(id,{...input,scheduledAt:input.scheduledAt?new Date(input.scheduledAt):undefined,estimatedEffortHours:input.estimatedEffortHours?dec(input.estimatedEffortHours):undefined}); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'SITE_SURVEY_UPDATED',subjectType:'SiteSurvey',subjectId:id,beforeJson:before,afterJson:toCrmDto(row),ip:actor.ip}); return toCrmDto(row);}); }

  listQuotations(t: TenantRequestContext, q: any) { return this.listModel(t, 'quotation', q); }
  getQuotation(t: TenantRequestContext, id: string) { return this.getModel(t, 'quotation', id, 'QUOTATION_NOT_FOUND'); }
  createQuotation(t: TenantRequestContext, actor: any, input: any) { return this.numbers.withBusinessNumber({organizationId:t.organizationId,branchId:t.branchId,entityType:'QUOTATION',fiscalYear:new Date().getUTCFullYear(),targetType:'Quotation',createTarget:async(tx,quotationNo)=>{ const subtotal=input.items.reduce((sum:any,item:any)=>sum.add(dec(item.quantity).mul(dec(item.unitPrice))),new Prisma.Decimal(0)); const row=await this.repository.withDb(tx).createQuotation({organizationId:t.organizationId,quotationNo,opportunityId:input.opportunityId??null,customerId:input.customerId,siteId:input.siteId??null,validUntil:date(input.validUntil),currency:input.currency,subtotal,taxTotal:new Prisma.Decimal(0),total:subtotal,terms:input.terms??null,status:'DRAFT',createdById:actor.userId}, input.items.map((item:any)=>{const qty=dec(item.quantity),price=dec(item.unitPrice);return{organizationId:t.organizationId,productId:item.productId??null,description:item.description,quantity:qty,unitPrice:price,lineTotal:qty.mul(price),taxCodeId:item.taxCodeId??null};})); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'QUOTATION_CREATED',subjectType:'Quotation',subjectId:row.id,afterJson:toCrmDto(row),ip:actor.ip}); return row;}}); }
  async updateQuotation(t: TenantRequestContext, actor: any, id: string, input: any) { const before=await this.getQuotation(t,id); return withTransaction(async tx=>{ const row=await this.repository.withDb(tx).updateQuotation(id,{...input,validUntil:input.validUntil?date(input.validUntil):undefined}); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'QUOTATION_UPDATED',subjectType:'Quotation',subjectId:id,beforeJson:before,afterJson:toCrmDto(row),ip:actor.ip}); return toCrmDto(row);}); }
  async sendQuotation(t: TenantRequestContext, actor: any, id: string, input: any) { const q=await this.getQuotation(t,id); if(q.status!=='DRAFT') throw new AppError(409,'QUOTATION_NOT_SENDABLE','Only DRAFT quotations can be sent.'); return withTransaction(async tx=>{ const row=await this.repository.withDb(tx).updateQuotation(id,{status:'SENT',sentAt:new Date()}); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'QUOTATION_SENT',subjectType:'Quotation',subjectId:id,beforeJson:q,afterJson:toCrmDto(row),ip:actor.ip}); await this.events.append(tx,{organizationId:t.organizationId,type:'quotation.send.requested',aggregateType:'Quotation',aggregateId:id,payload:{message:input.message??null}}); return toCrmDto(row);}); }
  async acceptQuotation(t: TenantRequestContext, actor: any, id: string, input: any) { const quote=await this.getQuotation(t,id); if(!['SENT','DRAFT'].includes(quote.status)) throw new AppError(409,'QUOTATION_NOT_ACCEPTABLE','Quotation cannot be accepted from its current status.'); return withTransaction(async tx=>{ const repo=this.repository.withDb(tx); const row=await repo.updateQuotation(id,{status:'ACCEPTED',acceptedAt:input.acceptedAt?new Date(input.acceptedAt):new Date(),acceptedByName:input.acceptedByName}); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'QUOTATION_ACCEPTED',subjectType:'Quotation',subjectId:id,beforeJson:quote,afterJson:toCrmDto(row),ip:actor.ip}); return toCrmDto(row); }); }

  listContracts(t: TenantRequestContext, q: any) { return this.listModel(t, 'customerContract', q); }
  getContract(t: TenantRequestContext, id: string) { return this.getModel(t, 'customerContract', id, 'CONTRACT_NOT_FOUND'); }
  createContract(t: TenantRequestContext, actor: any, input: any) { return this.numbers.withBusinessNumber({organizationId:t.organizationId,branchId:t.branchId,entityType:'CUSTOMER_CONTRACT',fiscalYear:new Date(input.startDate).getUTCFullYear(),targetType:'CustomerContract',createTarget:async(tx,contractNo)=>{ const row=await this.repository.withDb(tx).createContract({organizationId:t.organizationId,contractNo,customerId:input.customerId,siteId:input.siteId??null,quotationId:input.quotationId??null,title:input.title,startDate:date(input.startDate),endDate:date(input.endDate),billingCycle:input.billingCycle,amount:dec(input.amount),terms:input.terms??null,status:'DRAFT',createdById:actor.userId}); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'CUSTOMER_CONTRACT_CREATED',subjectType:'CustomerContract',subjectId:row.id,afterJson:toCrmDto(row),ip:actor.ip}); return row;}}); }
  async updateContract(t: TenantRequestContext, actor: any, id: string, input: any) { const before=await this.getContract(t,id); return withTransaction(async tx=>{ const row=await this.repository.withDb(tx).updateContract(id,{...input,startDate:input.startDate?date(input.startDate):undefined,endDate:input.endDate?date(input.endDate):undefined,amount:input.amount?dec(input.amount):undefined}); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'CUSTOMER_CONTRACT_UPDATED',subjectType:'CustomerContract',subjectId:id,beforeJson:before,afterJson:toCrmDto(row),ip:actor.ip}); return toCrmDto(row);}); }
  async activateContract(t: TenantRequestContext, actor: any, id: string, input: any) { const before=await this.getContract(t,id); if (before.status !== 'DRAFT') throw new AppError(409,'CONTRACT_NOT_ACTIVATABLE','Only DRAFT contracts can be activated.'); return withTransaction(async tx=>{ const row=await this.repository.withDb(tx).updateContract(id,{status:'ACTIVE',activatedAt:new Date()}); await this.audit.append(tx,{organizationId:t.organizationId,actorUserId:actor.userId,action:'CUSTOMER_CONTRACT_ACTIVATED',subjectType:'CustomerContract',subjectId:id,beforeJson:before,afterJson:{...toCrmDto(row),activationNote:input.activationNote??null},ip:actor.ip}); return toCrmDto(row);}); }
}
