export const ApprovalEnginePassC5Manifest = {
  pass: 'C5_APPROVAL_ENGINE_MAKER_CHECKER',
  lockedPurpose:
    'Complete configurable approvals and maker-checker controls without bypassing tenant scope, service ownership, transactions or audit.',
  approvedSubjectTypes: [
    'PurchaseRequest',
    'PurchaseOrder',
    'StockAdjustment',
    'StockCountVariance',
    'VendorOnboardingRequest',
    'CustomerInvoice',
    'SupplierInvoice',
    'Expense',
    'Payment',
    'LeaveRequest',
    'PayrollRun',
    'AssetRetirement',
    'AssetDisposal',
    'PurchaseContract',
    'PurchaseReleaseOrder',
    'LandedCost',
    'BankReconciliation',
    'PaymentVoucher',
    'ReceiptVoucher',
  ],
  commandEndpoints: [
    'GET /api/v1/approvals/inbox',
    'GET /api/v1/approvals/:id',
    'POST /api/v1/approvals/:id/approve',
    'POST /api/v1/approvals/:id/reject',
    'POST /api/v1/approvals/:id/return',
    'GET /api/v1/approval-definitions',
    'POST /api/v1/approval-definitions',
  ],
  mandatoryStateControls: [
    'approval-definitions-are-tenant-owned-and-condition-driven',
    'approval-requests-are-created-inside-the-originating-domain-transaction',
    'approval-actions-lock-the-current-request-and-current-step',
    'only-current-pending-step-can-be-acted-on',
    'eligible-approver-is-resolved-from-user-or-role-membership',
    'maker-checker-blocks-creator-self-approval-for-high-risk-subjects',
    'reject-action-requires-comment',
    'return-action-reopens-originating-subject-according-to-domain-facade',
    'approved-final-step-applies-subject-decision-inside-the-same-transaction',
    'every-decision-produces-stable-audit-action-name',
    'high-risk-payment-stock-count-voucher-and-bank-reconciliation-subjects-are-governed',
    'fraud-control-rules-can-block-or-require-secondary-approval',
    'workflow-rules-are-tenant-owned-and-managed-through-workflow.manage',
  ],
  forbiddenPatterns: [
    'no-approval-decision-from-frontend-status-patch',
    'no-direct-prisma-access-from-approval-routes-or-controllers',
    'no-cross-domain-private-repository-imports',
    'no-async-approval-state-mutation-through-bullmq',
    'no-organizationId-override-from-request-body',
  ],
  runtimeEvidenceRequired: [
    'creator-cannot-self-approve-high-risk-subject',
    'role-step-approver-can-approve-when-membership-is-active',
    'ineligible-user-cannot-act-on-step',
    'second-action-by-same-actor-is-rejected',
    'multi-step-workflow-activates-next-step-only-after-min-approvals',
    'final-approval-updates-subject-via-registered-domain-decision-handler',
    'rejection-comment-is-required-and-subject-is-rejected',
    'returned-request-is-audited-and-subject-is-returned-for-correction',
    'cross-tenant-approval-idor-is-denied',
    'stock-count-variance-route-requires-approval',
    'workflow-rule-evaluation-is-tenant-scoped',
    'fraud-rule-blocks-over-po-supplier-invoice',
  ],
} as const;

export type ApprovalEngineApprovedSubjectType =
  (typeof ApprovalEnginePassC5Manifest.approvedSubjectTypes)[number];
