import type { PermissionKey } from '@nexora/shared';
import type { EntityColumnConfig } from '@/modules/masters/columns';

export type PortalResourceKey =
  | 'customer-projects' | 'customer-contracts' | 'customer-sites' | 'customer-assets' | 'customer-tickets' | 'customer-invoices' | 'customer-payments' | 'customer-documents'
  | 'vendor-rfqs' | 'vendor-quotations' | 'vendor-purchase-orders' | 'vendor-deliveries' | 'vendor-invoices' | 'vendor-payments' | 'vendor-performance' | 'vendor-documents';

export type PortalResourceConfig = { key: PortalResourceKey; title: string; routeBase: string; endpoint: string; viewPermission: PermissionKey; description: string; columns: readonly EntityColumnConfig[]; linkedScope: 'customer' | 'vendor'; actions: readonly string[] };

const baseColumns: EntityColumnConfig[] = [{ key: 'businessNo', label: 'No' }, { key: 'title', label: 'Title' }, { key: 'status', label: 'Status' }, { key: 'updatedAt', label: 'Updated' }];
const moneyColumns: EntityColumnConfig[] = [{ key: 'invoiceNo', label: 'Invoice' }, { key: 'total', label: 'Total' }, { key: 'balance', label: 'Balance' }, { key: 'status', label: 'Status' }];
const docColumns: EntityColumnConfig[] = [{ key: 'fileName', label: 'File' }, { key: 'category', label: 'Category' }, { key: 'createdAt', label: 'Uploaded' }];

export const PortalResourceConfigs = {
  'customer-projects': { key: 'customer-projects', title: 'My Projects', routeBase: '/customer-portal/projects', endpoint: '/portal/customer/projects', viewPermission: 'customer.view', linkedScope: 'customer', description: 'Customer-linked project progress and handover evidence without internal ERP navigation.', columns: baseColumns, actions: ['View progress', 'Open timeline', 'Download handover package'] },
  'customer-contracts': { key: 'customer-contracts', title: 'My Contracts', routeBase: '/customer-portal/contracts', endpoint: '/portal/customer/contracts', viewPermission: 'customer.view', linkedScope: 'customer', description: 'Customer contracts, service packages, expiries and warranties for the authenticated linked customer.', columns: baseColumns, actions: ['View contract', 'Download document'] },
  'customer-sites': { key: 'customer-sites', title: 'My Sites', routeBase: '/customer-portal/sites', endpoint: '/portal/customer/sites', viewPermission: 'customer.view', linkedScope: 'customer', description: 'Customer site hierarchy and installed asset location visibility.', columns: baseColumns, actions: ['View site', 'Open assets'] },
  'customer-assets': { key: 'customer-assets', title: 'My Assets', routeBase: '/customer-portal/assets', endpoint: '/portal/customer/assets', viewPermission: 'asset.view', linkedScope: 'customer', description: 'Customer-installed assets, warranty state, QR history and service history.', columns: baseColumns, actions: ['View asset', 'Create ticket'] },
  'customer-tickets': { key: 'customer-tickets', title: 'My Tickets', routeBase: '/customer-portal/tickets', endpoint: '/portal/customer/tickets', viewPermission: 'ticket.view', linkedScope: 'customer', description: 'Customer ticket submission and work-order/customer confirmation tracking.', columns: baseColumns, actions: ['Submit ticket', 'Approve completed work'] },
  'customer-invoices': { key: 'customer-invoices', title: 'My Invoices', routeBase: '/customer-portal/invoices', endpoint: '/portal/customer/invoices', viewPermission: 'invoice.view', linkedScope: 'customer', description: 'Customer invoices, balances, downloads and payment status.', columns: moneyColumns, actions: ['Download invoice', 'View payment allocation'] },
  'customer-payments': { key: 'customer-payments', title: 'My Payments', routeBase: '/customer-portal/payments', endpoint: '/portal/customer/payments', viewPermission: 'payment.view', linkedScope: 'customer', description: 'Customer payment receipts and allocations.', columns: moneyColumns, actions: ['Download receipt'] },
  'customer-documents': { key: 'customer-documents', title: 'My Documents', routeBase: '/customer-portal/documents', endpoint: '/portal/customer/documents', viewPermission: 'document.view', linkedScope: 'customer', description: 'Authorized customer project, contract, invoice and handover documents.', columns: docColumns, actions: ['Download authorized document'] },
  'vendor-rfqs': { key: 'vendor-rfqs', title: 'New RFQs', routeBase: '/vendor-portal/rfqs', endpoint: '/portal/vendor/rfqs', viewPermission: 'rfq.view', linkedScope: 'vendor', description: 'Vendor-linked RFQs awaiting quotation responses.', columns: baseColumns, actions: ['Review RFQ', 'Submit quotation'] },
  'vendor-quotations': { key: 'vendor-quotations', title: 'Submitted Quotations', routeBase: '/vendor-portal/quotations', endpoint: '/portal/vendor/quotations', viewPermission: 'supplier_quotation.view', linkedScope: 'vendor', description: 'Supplier quotations submitted by the linked vendor.', columns: baseColumns, actions: ['View quotation', 'Track selection'] },
  'vendor-purchase-orders': { key: 'vendor-purchase-orders', title: 'Purchase Orders', routeBase: '/vendor-portal/purchase-orders', endpoint: '/portal/vendor/purchase-orders', viewPermission: 'purchase_order.view', linkedScope: 'vendor', description: 'Vendor purchase orders, status, delivery schedule and sent PO documents.', columns: baseColumns, actions: ['Acknowledge PO', 'View delivery schedule'] },
  'vendor-deliveries': { key: 'vendor-deliveries', title: 'Deliveries and GRNs', routeBase: '/vendor-portal/deliveries', endpoint: '/portal/vendor/deliveries', viewPermission: 'goods_receipt.view', linkedScope: 'vendor', description: 'Vendor delivery state, goods receipt notes and rejected item visibility.', columns: baseColumns, actions: ['View GRN', 'Review rejected items'] },
  'vendor-invoices': { key: 'vendor-invoices', title: 'Supplier Invoices', routeBase: '/vendor-portal/invoices', endpoint: '/portal/vendor/invoices', viewPermission: 'supplier_invoice.view', linkedScope: 'vendor', description: 'Vendor invoice status, three-way match result and payment readiness.', columns: moneyColumns, actions: ['Submit invoice', 'View match result'] },
  'vendor-payments': { key: 'vendor-payments', title: 'Payments', routeBase: '/vendor-portal/payments', endpoint: '/portal/vendor/payments', viewPermission: 'payment.view', linkedScope: 'vendor', description: 'Outbound payments and allocation history for the linked vendor.', columns: moneyColumns, actions: ['View remittance'] },
  'vendor-performance': { key: 'vendor-performance', title: 'Performance', routeBase: '/vendor-portal/performance', endpoint: '/portal/vendor/performance', viewPermission: 'vendor.view', linkedScope: 'vendor', description: 'Vendor performance metrics, on-time delivery and rejection percentage.', columns: baseColumns, actions: ['View performance score'] },
  'vendor-documents': { key: 'vendor-documents', title: 'Documents', routeBase: '/vendor-portal/documents', endpoint: '/portal/vendor/documents', viewPermission: 'document.view', linkedScope: 'vendor', description: 'Vendor contracts, POs, invoices and delivery documents authorized for the linked supplier.', columns: docColumns, actions: ['Download authorized document'] },
} satisfies Record<PortalResourceKey, PortalResourceConfig>;

export function getPortalResourceConfig(key: PortalResourceKey): PortalResourceConfig { return PortalResourceConfigs[key]; }
