import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
const root = process.cwd();
const failures = [];
const prior = spawnSync(process.execPath, ['scripts/check-enterprise-controls.mjs'], { stdio: 'inherit' });
if (prior.status !== 0) process.exit(prior.status ?? 1);
const lock = JSON.parse(readFileSync(join(root, 'docs/contracts/capability-locks/hr.json'), 'utf8'));
const catalog = readFileSync(join(root, 'docs/contracts/api-endpoint-matrix.csv'), 'utf8');
const routeFiles = ['backend/src/modules/hr/employee/employee.routes.ts','backend/src/modules/hr/attendance/attendance.routes.ts','backend/src/modules/hr/leave/leave.routes.ts','backend/src/modules/hr/payroll/payroll.routes.ts'].map(p => readFileSync(join(root,p),'utf8')).join('\n');
for (const route of lock.lockedRoutes) { const sig = `defineLockedRoute('${route.method}', '${route.path}')`; if (!routeFiles.includes(sig)) failures.push(`Missing locked HR route: ${route.method} ${route.path}`); if (!catalog.includes(route.path)) failures.push(`Route absent frozen catalog: ${route.path}`); if (!routeFiles.includes(`'${route.permission}'`)) failures.push(`Permission guard missing: ${route.permission}`); }
const routeMatches = [...routeFiles.matchAll(/defineLockedRoute\('([A-Z]+)', '([^']+)'\)/g)].map(m => `${m[1]} ${m[2]}`);
if (new Set(routeMatches).size !== lock.lockedRouteCount) failures.push(`Expected ${lock.lockedRouteCount} HR routes, found ${new Set(routeMatches).size}`);
const schema = readFileSync(join(root,'database/prisma/schema.prisma'),'utf8');
for (const model of lock.newPhysicalModels) if (!new RegExp(`model\\s+${model}\\s*\\{`).test(schema)) failures.push(`Missing Prisma model: ${model}`);
for (const field of ['baseSalary','allowancesJson','leaveRequest LeaveRequest? @relation("LeaveRequestApproval")','payrollRun PayrollRun? @relation("PayrollRunApproval")']) if (!schema.includes(field)) failures.push(`Schema invariant missing: ${field}`);
if (/\bFloat\b/.test(schema)) failures.push('Float introduced into Prisma schema.');
const migration = readFileSync(join(root,'database/prisma/migrations/20260903000900_pass17_hr/migration.sql'),'utf8');
for (const invariant of ['Attendance_status_check','Attendance_method_check','LeaveBalance_non_negative_check','LeaveRequest_status_check','PayrollRun_status_check','PayrollRun_organizationId_idempotencyKey_key','PayrollItem_non_negative_check']) if (!migration.includes(invariant)) failures.push(`Migration invariant missing: ${invariant}`);
const leaveService = readFileSync(join(root,'backend/src/modules/hr/leave/leave.service.ts'),'utf8');
for (const invariant of ['requestApprovalIfConfigured','LEAVE_BALANCE_INSUFFICIENT','LEAVE_REQUEST_SUBMITTED','LEAVE_APPROVAL_APPLIED','leave_request.submitted']) if (!leaveService.includes(invariant)) failures.push(`Leave invariant missing: ${invariant}`);
if (/\btx\s*\.\s*[a-zA-Z]\w*\s*\./.test(leaveService)) failures.push('LeaveService must persist through repository/facades only.');
const payrollService = readFileSync(join(root,'backend/src/modules/hr/payroll/payroll.service.ts'),'utf8');
for (const invariant of ['PAYROLL_MAKER_CHECKER_DENIED','IDEMPOTENCY_KEY_REQUIRED','this.finance.postCommercialJournal','PAYROLL_RUN_CALCULATED','PAYROLL_RUN_APPROVED','PAYROLL_RUN_POSTED',"type: 'payroll_run.posted'"]) if (!payrollService.includes(invariant)) failures.push(`Payroll invariant missing: ${invariant}`);
if (/\btx\s*\.\s*[a-zA-Z]\w*\s*\./.test(payrollService)) failures.push('PayrollService must persist through repository/facades only.');
const attendanceService = readFileSync(join(root,'backend/src/modules/hr/attendance/attendance.service.ts'),'utf8');
if (!attendanceService.includes('ATTENDANCE_BRANCH_SCOPE_DENIED')) failures.push('Attendance branch scope invariant missing.');
const hrModule = readFileSync(join(root,'backend/src/modules/hr/hr.module.ts'),'utf8');
for (const invariant of ['attendanceRoutes','leaveRoutes','payrollRoutes','HrFacade','FinanceFacade','ApprovalFacade']) if (!hrModule.includes(invariant)) failures.push(`HR module composition missing: ${invariant}`);
const app = readFileSync(join(root,'backend/src/app.ts'),'utf8');
for (const invariant of ["const hr = createHrModule", "approvalSubjects.register('LeaveRequest', hr.facade)", "approvalSubjects.register('PayrollRun', hr.facade)", 'app.register(hr.plugin']) if (!app.includes(invariant)) failures.push(`App composition missing: ${invariant}`);
const employeeRepo = readFileSync(join(root,'backend/src/modules/hr/employee/employee.repository.ts'),'utf8');
if (!employeeRepo.includes('findByUser')) failures.push('EmployeeFacade repository method findByUser missing.');
for (const file of ['backend/src/modules/hr/attendance/attendance.repository.ts','backend/src/modules/hr/leave/leave.repository.ts','backend/src/modules/hr/payroll/payroll.repository.ts','backend/src/modules/hr/hr.facade.ts','frontend/src/app/(erp)/attendance/page.tsx','frontend/src/app/(erp)/leave-requests/page.tsx','frontend/src/app/(erp)/payroll-runs/page.tsx','docs/architecture/source-boundaries/hr.md']) if (!existsSync(join(root,file))) failures.push(`Missing file: ${file}`);
const allHrBackend = [leaveService, payrollService, attendanceService, routeFiles].join('\n');
if (allHrBackend.includes('BullMQ') || allHrBackend.includes("from 'bullmq'")) failures.push('Critical HR financial/leave state must not use BullMQ directly.');
if (allHrBackend.includes('@aws-sdk/client-s3') || allHrBackend.includes("from 'minio'")) failures.push('HR must not use object storage SDK directly.');
const pkg = JSON.parse(readFileSync(join(root,'package.json'),'utf8'));
if (!String(pkg.scripts?.['verify:static'] ?? '').includes('hr:check')) failures.push('verify:static does not include hr:check.');
if (!String(pkg.scripts?.verify ?? '').includes('hr:check')) failures.push('verify does not include hr:check.');
if (failures.length) { console.error('HR gate FAILED'); for (const failure of failures) console.error(`- ${failure}`); process.exit(1); }
console.log(`HR gate PASSED: ${lock.lockedRouteCount} exact HR routes and ${lock.newPhysicalModelCount} new HR models.`);
