import type { PermissionKey } from './permissions';

export type FrontendRouteContract = {
  route: string;
  routeGroup: '(auth)' | '(erp)' | '(portal)' | '(technician)';
  owner: string;
  shell: 'AuthLayout' | 'AppShell' | 'PortalShell' | 'TechnicianPwaShell';
  requiredPermissions: readonly PermissionKey[] | 'authenticated' | 'public';
  backendEndpoints: readonly string[];
};

export const FRONTEND_ROUTE_MAP = [
  { route: '/login', routeGroup: '(auth)', owner: 'identity', shell: 'AuthLayout', requiredPermissions: 'public', backendEndpoints: ['/auth/login', '/auth/mfa/verify'] },
  { route: '/', routeGroup: '(erp)', owner: 'dashboard', shell: 'AppShell', requiredPermissions: 'authenticated', backendEndpoints: ['/auth/me', '/features'] },
  { route: '/organization', routeGroup: '(erp)', owner: 'organization', shell: 'AppShell', requiredPermissions: ['organization.view'], backendEndpoints: ['/branches', '/departments', '/features', '/number-sequences'] },
  { route: '/users', routeGroup: '(erp)', owner: 'identity', shell: 'AppShell', requiredPermissions: ['identity.user.view'], backendEndpoints: ['/users', '/users/:id', '/roles'] },
  { route: '/roles', routeGroup: '(erp)', owner: 'identity', shell: 'AppShell', requiredPermissions: ['identity.role.manage'], backendEndpoints: ['/roles', '/roles/:id', '/permissions'] },
  { route: '/permissions', routeGroup: '(erp)', owner: 'identity', shell: 'AppShell', requiredPermissions: ['identity.role.manage'], backendEndpoints: ['/permissions', '/roles'] },
  { route: '/rbac', routeGroup: '(erp)', owner: 'identity', shell: 'AppShell', requiredPermissions: ['identity.role.manage'], backendEndpoints: ['/roles', '/permissions'] },
  { route: '/organization-settings', routeGroup: '(erp)', owner: 'organization', shell: 'AppShell', requiredPermissions: ['organization.manage'], backendEndpoints: ['/features', '/organization-features', '/module-configurations/:id'] },
  { route: '/teams', routeGroup: '(erp)', owner: 'organization', shell: 'AppShell', requiredPermissions: ['organization.view'], backendEndpoints: ['/teams', '/teams/:id'] },
  { route: '/number-sequences', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['number_sequence.manage'], backendEndpoints: ['/number-sequences', '/number-sequences/:id/reset'] },
  { route: '/customers', routeGroup: '(erp)', owner: 'crm', shell: 'AppShell', requiredPermissions: ['customer.view'], backendEndpoints: ['/customers', '/customers/:id'] },
  { route: '/vendors', routeGroup: '(erp)', owner: 'vendors', shell: 'AppShell', requiredPermissions: ['vendor.view'], backendEndpoints: ['/vendors', '/vendors/:id'] },
  { route: '/products', routeGroup: '(erp)', owner: 'inventory', shell: 'AppShell', requiredPermissions: ['product.view'], backendEndpoints: ['/products', '/products/:id'] },
  { route: '/warehouses', routeGroup: '(erp)', owner: 'inventory', shell: 'AppShell', requiredPermissions: ['warehouse.view'], backendEndpoints: ['/warehouses', '/warehouses/:id'] },
  { route: '/procurement/purchase-requests', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['purchase_request.view'], backendEndpoints: ['/purchase-requests', '/purchase-requests/:id/submit', '/purchase-requests/:id/approve', '/purchase-requests/:id/reject'] },
  { route: '/inventory/stock', routeGroup: '(erp)', owner: 'inventory', shell: 'AppShell', requiredPermissions: ['inventory.view'], backendEndpoints: ['/inventory/stock'] },
  { route: '/projects', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project.view'], backendEndpoints: ['/projects', '/projects/:id', '/projects/:id/timeline'] },
  { route: '/assets', routeGroup: '(erp)', owner: 'assets', shell: 'AppShell', requiredPermissions: ['asset.view'], backendEndpoints: ['/assets', '/assets/:id/history', '/assets/:id/qr/rotate'] },
  { route: '/tickets', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['ticket.view'], backendEndpoints: ['/tickets', '/tickets/:id/assign', '/tickets/:id/resolve', '/tickets/:id/close'] },
  { route: '/work-orders', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['workorder.view'], backendEndpoints: ['/work-orders', '/work-orders/:id/complete'] },
  { route: '/customer-invoices', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['invoice.view'], backendEndpoints: ['/customer-invoices', '/customer-invoices/:id/post', '/payments'] },
  { route: '/reports', routeGroup: '(erp)', owner: 'reports', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/reports', '/reports/exports'] },
  { route: '/documents', routeGroup: '(erp)', owner: 'documents', shell: 'AppShell', requiredPermissions: ['document.view'], backendEndpoints: ['/documents', '/documents/upload-intent', '/documents/complete-upload'] },
  { route: '/audit-logs', routeGroup: '(erp)', owner: 'audit', shell: 'AppShell', requiredPermissions: ['audit.view'], backendEndpoints: ['/audit-logs'] },
  { route: '/workflow-rules', routeGroup: '(erp)', owner: 'approvals', shell: 'AppShell', requiredPermissions: ['workflow.manage'], backendEndpoints: ['/workflow-rules', '/workflow-rules/:id', '/workflow-rules/evaluate'] },
  { route: '/customer-portal', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: 'authenticated', backendEndpoints: ['/portal/customer/dashboard'] },
  { route: '/vendor-portal', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: 'authenticated', backendEndpoints: ['/portal/vendor/dashboard'] },
  { route: '/technician-pwa', routeGroup: '(technician)', owner: 'portal', shell: 'TechnicianPwaShell', requiredPermissions: 'authenticated', backendEndpoints: ['/portal/technician/jobs', '/portal/technician/offline-sync'] },

  { route: '/employees/create', routeGroup: '(erp)', owner: 'hr', shell: 'AppShell', requiredPermissions: ['employee.create'], backendEndpoints: ['/employees'] },
  { route: '/employees/[id]', routeGroup: '(erp)', owner: 'hr', shell: 'AppShell', requiredPermissions: ['employee.view'], backendEndpoints: ['/employees/:id'] },
  { route: '/employees/[id]/edit', routeGroup: '(erp)', owner: 'hr', shell: 'AppShell', requiredPermissions: ['employee.update'], backendEndpoints: ['/employees/:id'] },
  { route: '/customers/create', routeGroup: '(erp)', owner: 'crm', shell: 'AppShell', requiredPermissions: ['customer.create'], backendEndpoints: ['/customers'] },
  { route: '/customers/[id]', routeGroup: '(erp)', owner: 'crm', shell: 'AppShell', requiredPermissions: ['customer.view'], backendEndpoints: ['/customers/:id', '/customers/:id/timeline'] },
  { route: '/customers/[id]/edit', routeGroup: '(erp)', owner: 'crm', shell: 'AppShell', requiredPermissions: ['customer.update'], backendEndpoints: ['/customers/:id'] },
  { route: '/customer-sites/create', routeGroup: '(erp)', owner: 'crm', shell: 'AppShell', requiredPermissions: ['customer_site.create'], backendEndpoints: ['/customer-sites'] },
  { route: '/customer-sites/[id]', routeGroup: '(erp)', owner: 'crm', shell: 'AppShell', requiredPermissions: ['customer_site.view'], backendEndpoints: ['/customer-sites/:id', '/customer-sites/:id/assets'] },
  { route: '/customer-sites/[id]/edit', routeGroup: '(erp)', owner: 'crm', shell: 'AppShell', requiredPermissions: ['customer_site.update'], backendEndpoints: ['/customer-sites/:id'] },
  { route: '/vendors/create', routeGroup: '(erp)', owner: 'vendors', shell: 'AppShell', requiredPermissions: ['vendor.create'], backendEndpoints: ['/vendors'] },
  { route: '/vendors/[id]', routeGroup: '(erp)', owner: 'vendors', shell: 'AppShell', requiredPermissions: ['vendor.view'], backendEndpoints: ['/vendors/:id', '/vendors/:id/performance', '/vendors/:id/purchase-orders'] },
  { route: '/vendors/[id]/edit', routeGroup: '(erp)', owner: 'vendors', shell: 'AppShell', requiredPermissions: ['vendor.update'], backendEndpoints: ['/vendors/:id'] },
  { route: '/products/create', routeGroup: '(erp)', owner: 'inventory', shell: 'AppShell', requiredPermissions: ['product.create'], backendEndpoints: ['/products'] },
  { route: '/products/[id]', routeGroup: '(erp)', owner: 'inventory', shell: 'AppShell', requiredPermissions: ['product.view'], backendEndpoints: ['/products/:id', '/inventory/stock', '/inventory/ledger'] },
  { route: '/products/[id]/edit', routeGroup: '(erp)', owner: 'inventory', shell: 'AppShell', requiredPermissions: ['product.update'], backendEndpoints: ['/products/:id'] },
  { route: '/warehouses/create', routeGroup: '(erp)', owner: 'inventory', shell: 'AppShell', requiredPermissions: ['warehouse.create'], backendEndpoints: ['/warehouses'] },
  { route: '/warehouses/[id]', routeGroup: '(erp)', owner: 'inventory', shell: 'AppShell', requiredPermissions: ['warehouse.view'], backendEndpoints: ['/warehouses/:id', '/inventory/stock', '/inventory/ledger'] },
  { route: '/warehouses/[id]/edit', routeGroup: '(erp)', owner: 'inventory', shell: 'AppShell', requiredPermissions: ['warehouse.update'], backendEndpoints: ['/warehouses/:id'] },
  { route: '/procurement/purchase-requests/create', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['purchase_request.create'], backendEndpoints: ["/purchase-requests"] },
  { route: '/procurement/purchase-requests/[id]', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['purchase_request.view'], backendEndpoints: ["/purchase-requests", "/purchase-requests/:id"] },
  { route: '/procurement/purchase-requests/[id]/edit', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['purchase_request.update'], backendEndpoints: ["/purchase-requests/:id"] },
  { route: '/procurement/rfqs', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['rfq.view'], backendEndpoints: ["/rfqs"] },
  { route: '/procurement/rfqs/create', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['rfq.create'], backendEndpoints: ["/rfqs"] },
  { route: '/procurement/rfqs/[id]', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['rfq.view'], backendEndpoints: ["/rfqs", "/rfqs/:id"] },
  { route: '/procurement/rfqs/[id]/comparison', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['supplier_quotation.view'], backendEndpoints: ["/rfqs/:id/comparison", "/supplier-quotations/:id/select"] },
  { route: '/procurement/supplier-quotations', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['supplier_quotation.view'], backendEndpoints: ["/supplier-quotations"] },
  { route: '/procurement/supplier-quotations/create', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['supplier_quotation.create'], backendEndpoints: ["/supplier-quotations"] },
  { route: '/procurement/supplier-quotations/[id]', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['supplier_quotation.view'], backendEndpoints: ["/supplier-quotations", "/supplier-quotations/:id"] },
  { route: '/procurement/purchase-orders', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['purchase_order.view'], backendEndpoints: ["/purchase-orders"] },
  { route: '/procurement/purchase-orders/create', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['purchase_order.create'], backendEndpoints: ["/purchase-orders"] },
  { route: '/procurement/purchase-orders/[id]', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['purchase_order.view'], backendEndpoints: ["/purchase-orders", "/purchase-orders/:id"] },
  { route: '/procurement/goods-receipts', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['goods_receipt.view'], backendEndpoints: ["/goods-receipts"] },
  { route: '/procurement/goods-receipts/create', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['goods_receipt.create'], backendEndpoints: ["/goods-receipts"] },
  { route: '/procurement/goods-receipts/[id]', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['goods_receipt.view'], backendEndpoints: ["/goods-receipts", "/goods-receipts/:id"] },
  { route: '/procurement/purchase-contracts', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['purchase_contract.manage'], backendEndpoints: ["/purchase-contracts"] },
  { route: '/procurement/purchase-contracts/create', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['purchase_contract.manage'], backendEndpoints: ["/purchase-contracts"] },
  { route: '/procurement/purchase-contracts/[id]', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['purchase_contract.manage'], backendEndpoints: ["/purchase-contracts", "/purchase-contracts/:id"] },
  { route: '/procurement/landed-costs', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['landed_cost.manage'], backendEndpoints: ["/landed-costs"] },
  { route: '/procurement/landed-costs/create', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['landed_cost.manage'], backendEndpoints: ["/landed-costs"] },
  { route: '/procurement/landed-costs/[id]', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['landed_cost.manage'], backendEndpoints: ["/landed-costs", "/landed-costs/:id"] },
  { route: '/procurement/vendor-onboarding', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['vendor.onboard'], backendEndpoints: ["/vendor-onboarding/requests"] },
  { route: '/procurement/vendor-onboarding/create', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['vendor.onboard'], backendEndpoints: ["/vendor-onboarding/requests"] },
  { route: '/procurement/vendor-onboarding/[id]', routeGroup: '(erp)', owner: 'procurement', shell: 'AppShell', requiredPermissions: ['vendor.onboard'], backendEndpoints: ["/vendor-onboarding/requests", "/vendor-onboarding/requests/:id"] },

  { route: '/projects/create', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project.create'], backendEndpoints: ['/projects'] },
  { route: '/projects/[id]', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project.view'], backendEndpoints: ['/projects/:id', '/projects/:id/timeline'] },
  { route: '/projects/[id]/edit', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project.update'], backendEndpoints: ['/projects/:id'] },
  { route: '/projects/[id]/bom', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project.view'], backendEndpoints: ['/projects/:id/bom', '/projects/:id/bom/:bomId/approve'] },
  { route: '/projects/[id]/budget', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project.view'], backendEndpoints: ['/projects/:id/budget'] },
  { route: '/projects/[id]/costing', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project.view_financials'], backendEndpoints: ['/projects/:id/costing'] },
  { route: '/projects/[id]/material-request', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project.update'], backendEndpoints: ['/projects/:id/material-request'] },
  { route: '/projects/[id]/handover', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project.handover'], backendEndpoints: ['/projects/:id/handover'] },
  { route: '/projects/[id]/timeline', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project.view'], backendEndpoints: ['/projects/:id/timeline'] },
  { route: '/projects/assets-completion', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project.view'], backendEndpoints: ['/projects', '/project-tasks', '/assets'] },
  { route: '/project-tasks/create', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project_task.create'], backendEndpoints: ['/project-tasks'] },
  { route: '/project-tasks/[id]', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project_task.view'], backendEndpoints: ['/project-tasks/:id'] },
  { route: '/project-tasks/[id]/edit', routeGroup: '(erp)', owner: 'projects', shell: 'AppShell', requiredPermissions: ['project_task.update'], backendEndpoints: ['/project-tasks/:id'] },
  { route: '/assets/create', routeGroup: '(erp)', owner: 'assets', shell: 'AppShell', requiredPermissions: ['asset.create'], backendEndpoints: ['/assets'] },
  { route: '/assets/register-from-stock', routeGroup: '(erp)', owner: 'assets', shell: 'AppShell', requiredPermissions: ['asset.create'], backendEndpoints: ['/assets/register-from-stock'] },
  { route: '/assets/[id]', routeGroup: '(erp)', owner: 'assets', shell: 'AppShell', requiredPermissions: ['asset.view'], backendEndpoints: ['/assets/:id', '/assets/:id/history'] },
  { route: '/assets/[id]/edit', routeGroup: '(erp)', owner: 'assets', shell: 'AppShell', requiredPermissions: ['asset.update'], backendEndpoints: ['/assets/:id'] },
  { route: '/assets/[id]/history', routeGroup: '(erp)', owner: 'assets', shell: 'AppShell', requiredPermissions: ['asset.view'], backendEndpoints: ['/assets/:id/history'] },
  { route: '/assets/[id]/install', routeGroup: '(erp)', owner: 'assets', shell: 'AppShell', requiredPermissions: ['asset.install'], backendEndpoints: ['/assets/:id/install'] },
  { route: '/assets/[id]/replace', routeGroup: '(erp)', owner: 'assets', shell: 'AppShell', requiredPermissions: ['asset.replace'], backendEndpoints: ['/assets/:id/replace'] },
  { route: '/assets/[id]/retire', routeGroup: '(erp)', owner: 'assets', shell: 'AppShell', requiredPermissions: ['asset.retire'], backendEndpoints: ['/assets/:id/retire'] },
  { route: '/assets/[id]/qr', routeGroup: '(erp)', owner: 'assets', shell: 'AppShell', requiredPermissions: ['asset.manage_qr'], backendEndpoints: ['/assets/:id/qr/rotate', '/asset-qr/:token'] },
  { route: '/assets/[id]/rma', routeGroup: '(erp)', owner: 'assets', shell: 'AppShell', requiredPermissions: ['asset.rma'], backendEndpoints: ['/assets/:id/rma'] },

  { route: '/tickets/create', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['ticket.create'], backendEndpoints: ['/tickets'] },
  { route: '/tickets/[id]', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['ticket.view'], backendEndpoints: ['/tickets/:id', '/tickets/:id/assign', '/tickets/:id/resolve', '/tickets/:id/close'] },
  { route: '/tickets/[id]/edit', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['ticket.update'], backendEndpoints: ['/tickets/:id'] },
  { route: '/tickets/[id]/sla', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['ticket.view'], backendEndpoints: ['/tickets/:id'] },
  { route: '/work-orders/create', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['workorder.create'], backendEndpoints: ['/work-orders'] },
  { route: '/work-orders/[id]', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['workorder.view'], backendEndpoints: ['/work-orders/:id', '/work-orders/:id/service-report', '/work-orders/:id/complete'] },
  { route: '/work-orders/[id]/edit', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['workorder.update'], backendEndpoints: ['/work-orders/:id'] },
  { route: '/work-orders/[id]/assign', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['workorder.assign'], backendEndpoints: ['/work-orders/:id/assign'] },
  { route: '/work-orders/[id]/service-report', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['workorder.update'], backendEndpoints: ['/work-orders/:id/service-report'] },
  { route: '/work-orders/[id]/parts', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['workorder.update'], backendEndpoints: ['/work-orders/:id/service-report'] },
  { route: '/work-orders/[id]/technician-timeline', routeGroup: '(erp)', owner: 'service', shell: 'AppShell', requiredPermissions: ['workorder.view'], backendEndpoints: ['/work-orders/:id'] },
  { route: '/maintenance/create', routeGroup: '(erp)', owner: 'maintenance', shell: 'AppShell', requiredPermissions: ['maintenance.create'], backendEndpoints: ['/maintenance/plans'] },
  { route: '/maintenance/[id]', routeGroup: '(erp)', owner: 'maintenance', shell: 'AppShell', requiredPermissions: ['maintenance.view'], backendEndpoints: ['/maintenance/plans/:id'] },
  { route: '/maintenance/[id]/edit', routeGroup: '(erp)', owner: 'maintenance', shell: 'AppShell', requiredPermissions: ['maintenance.create'], backendEndpoints: ['/maintenance/plans/:id'] },
  { route: '/maintenance/schedule', routeGroup: '(erp)', owner: 'maintenance', shell: 'AppShell', requiredPermissions: ['maintenance.view'], backendEndpoints: ['/maintenance/schedule'] },
  { route: '/maintenance/schedule/[id]', routeGroup: '(erp)', owner: 'maintenance', shell: 'AppShell', requiredPermissions: ['maintenance.view'], backendEndpoints: ['/maintenance/schedule/:id', '/maintenance/schedules/:id/generate-work-order'] },
  { route: '/maintenance/schedule/[id]/generate-work-order', routeGroup: '(erp)', owner: 'maintenance', shell: 'AppShell', requiredPermissions: ['maintenance.execute'], backendEndpoints: ['/maintenance/schedules/:id/generate-work-order'] },
  { route: '/maintenance/executions/[id]/complete', routeGroup: '(erp)', owner: 'maintenance', shell: 'AppShell', requiredPermissions: ['maintenance.execute'], backendEndpoints: ['/maintenance/executions/:id/complete'] },
  { route: '/technician-pwa/jobs', routeGroup: '(technician)', owner: 'service', shell: 'TechnicianPwaShell', requiredPermissions: 'authenticated', backendEndpoints: ['/portal/technician/jobs'] },
  { route: '/technician-pwa/offline-queue', routeGroup: '(technician)', owner: 'service', shell: 'TechnicianPwaShell', requiredPermissions: 'authenticated', backendEndpoints: ['/portal/technician/jobs', '/portal/technician/offline-sync'] },
  { route: '/technician-pwa/sync', routeGroup: '(technician)', owner: 'service', shell: 'TechnicianPwaShell', requiredPermissions: 'authenticated', backendEndpoints: ['/portal/technician/offline-sync'] },
  { route: '/technician-pwa/scan', routeGroup: '(technician)', owner: 'service', shell: 'TechnicianPwaShell', requiredPermissions: 'authenticated', backendEndpoints: ['/asset-qr/:token'] },
  { route: '/technician-pwa/work-orders/[id]', routeGroup: '(technician)', owner: 'service', shell: 'TechnicianPwaShell', requiredPermissions: 'authenticated', backendEndpoints: ['/work-orders/:id'] },
  { route: '/technician-pwa/work-orders/[id]/service-report', routeGroup: '(technician)', owner: 'service', shell: 'TechnicianPwaShell', requiredPermissions: 'authenticated', backendEndpoints: ['/work-orders/:id/service-report'] },
  { route: '/technician-pwa/work-orders/[id]/parts', routeGroup: '(technician)', owner: 'service', shell: 'TechnicianPwaShell', requiredPermissions: 'authenticated', backendEndpoints: ['/work-orders/:id/service-report'] },

  // Pass R15 finance frontend completion routes
  { route: '/finance/completion', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['finance.view'], backendEndpoints: ['/customer-invoices', '/supplier-invoices', '/payments', '/finance/receivables', '/finance/payables'] },
  { route: '/finance/receivables', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['finance.view'], backendEndpoints: ['/finance/receivables'] },
  { route: '/finance/payables', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['finance.view'], backendEndpoints: ['/finance/payables'] },
  { route: '/finance/ar-aging', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['finance.view'], backendEndpoints: ['/finance/receivables'] },
  { route: '/finance/ap-aging', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['finance.view'], backendEndpoints: ['/finance/payables'] },
  { route: '/finance/bank-cash', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['bank.manage'], backendEndpoints: ['/bank-accounts', '/bank-statements/import', '/bank-reconciliations/:id/close', '/vouchers/payment', '/vouchers/receipt'] },
  { route: '/customer-invoices/create', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['invoice.create'], backendEndpoints: ['/customer-invoices'] },
  { route: '/customer-invoices/[id]', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['invoice.view'], backendEndpoints: ['/customer-invoices/:id'] },
  { route: '/customer-invoices/[id]/edit', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['invoice.update'], backendEndpoints: ['/customer-invoices/:id'] },
  { route: '/customer-invoices/[id]/submit', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['invoice.submit'], backendEndpoints: ['/customer-invoices/:id/submit'] },
  { route: '/customer-invoices/[id]/approve', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['invoice.approve'], backendEndpoints: ['/customer-invoices/:id/approve'] },
  { route: '/customer-invoices/[id]/post', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['invoice.post'], backendEndpoints: ['/customer-invoices/:id/post'] },
  { route: '/customer-invoices/[id]/send', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['invoice.send'], backendEndpoints: ['/customer-invoices/:id/send'] },
  { route: '/customer-invoices/[id]/cancel', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['invoice.cancel'], backendEndpoints: ['/customer-invoices/:id/cancel'] },
  { route: '/supplier-invoices/create', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['supplier_invoice.create'], backendEndpoints: ['/supplier-invoices'] },
  { route: '/supplier-invoices/[id]', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['supplier_invoice.view'], backendEndpoints: ['/supplier-invoices/:id'] },
  { route: '/supplier-invoices/[id]/edit', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['supplier_invoice.update'], backendEndpoints: ['/supplier-invoices/:id'] },
  { route: '/supplier-invoices/[id]/match', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['supplier_invoice.match'], backendEndpoints: ['/supplier-invoices/:id/match'] },
  { route: '/supplier-invoices/[id]/approve', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['supplier_invoice.approve'], backendEndpoints: ['/supplier-invoices/:id/approve'] },
  { route: '/payments/create', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['payment.create'], backendEndpoints: ['/payments'] },
  { route: '/payments/[id]', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['payment.view'], backendEndpoints: ['/payments/:id'] },
  { route: '/payments/[id]/allocations', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['payment.view'], backendEndpoints: ['/payments/:id'] },
  { route: '/expenses/create', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['expense.create'], backendEndpoints: ['/expenses'] },
  { route: '/expenses/[id]', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['expense.view'], backendEndpoints: ['/expenses/:id'] },
  { route: '/expenses/[id]/edit', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['expense.update'], backendEndpoints: ['/expenses/:id'] },
  { route: '/accounts', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['account.view'], backendEndpoints: ['/accounts'] },
  { route: '/accounts/[id]', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['account.view'], backendEndpoints: ['/accounts'] },
  { route: '/journal-entries', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['finance.view'], backendEndpoints: ['/journal-entries'] },
  { route: '/journal-entries/create', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['journal.create'], backendEndpoints: ['/journal-entries'] },
  { route: '/journal-entries/[id]', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['finance.view'], backendEndpoints: ['/journal-entries/:id'] },
  { route: '/journal-entries/[id]/post', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['journal.post'], backendEndpoints: ['/journal-entries/:id/post'] },
  { route: '/tax-codes', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['tax.manage'], backendEndpoints: ['/tax-codes', '/tax-rules'] },
  { route: '/tax-codes/create', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['tax.manage'], backendEndpoints: ['/tax-codes'] },
  { route: '/tax-codes/[id]', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['tax.manage'], backendEndpoints: ['/tax-codes'] },
  { route: '/tax-rules/create', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['tax.manage'], backendEndpoints: ['/tax-rules'] },
  { route: '/tax/calculate', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['tax.manage'], backendEndpoints: ['/tax/calculate'] },
  { route: '/tax/reports', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['tax.manage'], backendEndpoints: ['/tax/reports'] },
  { route: '/bank-accounts', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['bank.manage'], backendEndpoints: ['/bank-accounts'] },
  { route: '/bank-accounts/[id]', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['bank.manage'], backendEndpoints: ['/bank-accounts'] },
  { route: '/bank-statements/import', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['bank.manage'], backendEndpoints: ['/bank-statements/import'] },
  { route: '/bank-reconciliations/[id]/close', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['bank.manage'], backendEndpoints: ['/bank-reconciliations/:id/close'] },
  { route: '/vouchers/payment', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['bank.manage'], backendEndpoints: ['/vouchers/payment'] },
  { route: '/vouchers/receipt', routeGroup: '(erp)', owner: 'finance', shell: 'AppShell', requiredPermissions: ['bank.manage'], backendEndpoints: ['/vouchers/receipt'] },

  // Pass R16 platform, portals and reports completion routes
  { route: '/documents', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['document.view'], backendEndpoints: ['/documents'] },
  { route: '/documents/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['document.view'], backendEndpoints: ['/documents/:id'] },
  { route: '/reports', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/reports'] },
  { route: '/reports/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/reports/:id'] },
  { route: '/report-builder/templates', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report_builder.manage'], backendEndpoints: ['/report-templates'] },
  { route: '/report-builder/templates/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report_builder.manage'], backendEndpoints: ['/report-templates/:id'] },
  { route: '/report-builder/saved-reports', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report_builder.manage'], backendEndpoints: ['/saved-reports'] },
  { route: '/report-builder/saved-reports/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report_builder.manage'], backendEndpoints: ['/saved-reports/:id'] },
  { route: '/report-builder/scheduled-reports', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report_builder.manage'], backendEndpoints: ['/scheduled-reports'] },
  { route: '/report-builder/scheduled-reports/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report_builder.manage'], backendEndpoints: ['/scheduled-reports/:id'] },
  { route: '/report-executions', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/report-executions'] },
  { route: '/report-executions/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/report-executions/:id'] },
  { route: '/communications', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['communication.view'], backendEndpoints: ['/communications'] },
  { route: '/communications/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['communication.view'], backendEndpoints: ['/communications/:id'] },
  { route: '/communication-templates', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['communication.view'], backendEndpoints: ['/communication-templates'] },
  { route: '/communication-templates/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['communication.view'], backendEndpoints: ['/communication-templates/:id'] },
  { route: '/notifications', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['communication.view'], backendEndpoints: ['/notifications'] },
  { route: '/notifications/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['communication.view'], backendEndpoints: ['/notifications/:id'] },
  { route: '/audit-logs', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['audit.view'], backendEndpoints: ['/audit-logs'] },
  { route: '/audit-logs/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['audit.view'], backendEndpoints: ['/audit-logs/:id'] },
  { route: '/search', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/search'] },
  { route: '/search/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/search/:id'] },
  { route: '/calendar', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/calendar'] },
  { route: '/calendar/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/calendar/:id'] },
  { route: '/saas/plans', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['saas.manage'], backendEndpoints: ['/saas/plans'] },
  { route: '/saas/plans/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['saas.manage'], backendEndpoints: ['/saas/plans/:id'] },
  { route: '/saas/subscriptions', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['saas.manage'], backendEndpoints: ['/saas/subscriptions'] },
  { route: '/saas/subscriptions/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['saas.manage'], backendEndpoints: ['/saas/subscriptions/:id'] },
  { route: '/saas/usage', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['saas.manage'], backendEndpoints: ['/saas/usage'] },
  { route: '/saas/invoices', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['saas.manage'], backendEndpoints: ['/saas/invoices'] },
  { route: '/saas/invoices/create', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['saas.manage'], backendEndpoints: ['/saas/invoices'] },
  { route: '/saas/invoices/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['saas.manage'], backendEndpoints: ['/saas/invoices/:id'] },
  { route: '/saas/invoices/[id]/edit', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['saas.manage'], backendEndpoints: ['/saas/invoices/:id'] },
  { route: '/saas/usage/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['saas.manage'], backendEndpoints: ['/saas/usage/:id'] },
  { route: '/platform-features', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['feature.manage'], backendEndpoints: ['/features'] },
  { route: '/platform-features/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['feature.manage'], backendEndpoints: ['/features/:id'] },
  { route: '/module-configurations', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['feature.manage'], backendEndpoints: ['/module-configurations'] },
  { route: '/module-configurations/[id]', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['feature.manage'], backendEndpoints: ['/module-configurations/:id'] },
  { route: '/platform/completion', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['workflow.manage'], backendEndpoints: ['/documents', '/reports', '/communications', '/notifications', '/audit-logs', '/search', '/calendar'] },
  { route: '/documents/upload', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['document.create'], backendEndpoints: ['/documents/upload-intent', '/documents/complete-upload'] },
  { route: '/documents/[id]/download', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['document.view'], backendEndpoints: ['/documents/:id/download-url'] },
  { route: '/documents/[id]/versions', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['document.update'], backendEndpoints: ['/documents/:id/versions'] },
  { route: '/reports/exports', routeGroup: '(erp)', owner: 'reports', shell: 'AppShell', requiredPermissions: ['report.export'], backendEndpoints: ['/reports/exports'] },
  { route: '/reports/exports/[jobId]', routeGroup: '(erp)', owner: 'reports', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/reports/exports/:jobId'] },
  { route: '/communications/send', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['communication.send'], backendEndpoints: ['/communications/send'] },
  { route: '/communications/[id]/delivery', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['communication.view'], backendEndpoints: ['/communications/:id/delivery'] },
  { route: '/notifications/[id]/read', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['communication.view'], backendEndpoints: ['/notifications/:id/read'] },
  { route: '/notifications/read-all', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['communication.view'], backendEndpoints: ['/notifications/read-all'] },
  { route: '/module-configurations/[id]/features', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['feature.manage'], backendEndpoints: ['/organization-features', '/module-configurations/:id'] },
  { route: '/customer-portal/projects', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['customer.view'], backendEndpoints: ['/portal/customer/projects'] },
  { route: '/customer-portal/contracts', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['customer.view'], backendEndpoints: ['/portal/customer/contracts'] },
  { route: '/customer-portal/sites', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['customer.view'], backendEndpoints: ['/portal/customer/sites'] },
  { route: '/customer-portal/assets', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['customer.view'], backendEndpoints: ['/portal/customer/assets'] },
  { route: '/customer-portal/tickets', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['customer.view'], backendEndpoints: ['/portal/customer/tickets'] },
  { route: '/customer-portal/invoices', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['customer.view'], backendEndpoints: ['/portal/customer/invoices'] },
  { route: '/customer-portal/payments', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['customer.view'], backendEndpoints: ['/portal/customer/payments'] },
  { route: '/customer-portal/documents', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['customer.view'], backendEndpoints: ['/portal/customer/documents'] },
  { route: '/vendor-portal/rfqs', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['vendor.view'], backendEndpoints: ['/portal/vendor/rfqs'] },
  { route: '/vendor-portal/quotations', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['vendor.view'], backendEndpoints: ['/portal/vendor/quotations'] },
  { route: '/vendor-portal/purchase-orders', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['vendor.view'], backendEndpoints: ['/portal/vendor/purchase-orders'] },
  { route: '/vendor-portal/deliveries', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['vendor.view'], backendEndpoints: ['/portal/vendor/deliveries'] },
  { route: '/vendor-portal/invoices', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['vendor.view'], backendEndpoints: ['/portal/vendor/invoices'] },
  { route: '/vendor-portal/payments', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['vendor.view'], backendEndpoints: ['/portal/vendor/payments'] },
  { route: '/vendor-portal/performance', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['vendor.view'], backendEndpoints: ['/portal/vendor/performance'] },
  { route: '/vendor-portal/documents', routeGroup: '(portal)', owner: 'portal', shell: 'PortalShell', requiredPermissions: ['vendor.view'], backendEndpoints: ['/portal/vendor/documents'] },

  { route: '/saved-views', routeGroup: '(erp)', owner: 'reports', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/saved-views'] },
  { route: '/saved-views/create', routeGroup: '(erp)', owner: 'reports', shell: 'AppShell', requiredPermissions: ['report_builder.manage'], backendEndpoints: ['/saved-views'] },
  { route: '/saved-views/[id]', routeGroup: '(erp)', owner: 'reports', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/saved-views/:id'] },
  { route: '/saved-views/[id]/edit', routeGroup: '(erp)', owner: 'reports', shell: 'AppShell', requiredPermissions: ['report_builder.manage'], backendEndpoints: ['/saved-views/:id'] },
  { route: '/dashboards/widgets', routeGroup: '(erp)', owner: 'reports', shell: 'AppShell', requiredPermissions: ['report.view'], backendEndpoints: ['/dashboards/widgets'] },
  { route: '/dashboards/widgets/create', routeGroup: '(erp)', owner: 'reports', shell: 'AppShell', requiredPermissions: ['report_builder.manage'], backendEndpoints: ['/dashboards/widgets'] },
  { route: '/integrations/webhooks', routeGroup: '(erp)', owner: 'integrations', shell: 'AppShell', requiredPermissions: ['integration.webhook.view'], backendEndpoints: ['/integration-webhooks', '/integration-webhook-deliveries'] },
  { route: '/operations/readiness', routeGroup: '(erp)', owner: 'platform', shell: 'AppShell', requiredPermissions: ['audit.view'], backendEndpoints: ['/health/live', '/health/ready', '/audit-logs'] },
] satisfies readonly FrontendRouteContract[];

export function getFrontendRouteContract(route: string) {
  return FRONTEND_ROUTE_MAP.find((item) => item.route === route);
}
