import { Prisma, withTransaction } from '@nexora/database';
import { AuditWriter } from '../../core/audit/audit-writer.js';
import { AppError } from '../../core/http/errors.js';
import { SaaSRepository } from './saas.repository.js';
function page(query:{page?:number;pageSize?:number}){const current=Number(query.page??1); const pageSize=Math.min(Number(query.pageSize??25),100); return {page:current,pageSize,skip:(current-1)*pageSize,take:pageSize};}
function day(value?: string, end=false){return value ? new Date(`${value}T${end?'23:59:59.999':'00:00:00.000'}Z`) : null;}
export class SaaSService {
  constructor(private readonly repository = new SaaSRepository(), private readonly audit = new AuditWriter()) {}
  async plans(query:any={}){ return this.repository.listPlans(query); }
  async createPlan(actor:{userId:string;organizationId:string;ip:string|null}, input:any){ return withTransaction(async(tx)=>{ const plan=await this.repository.withDb(tx).createPlan(tx,{ key:input.key, name:input.name, moduleKeys:input.moduleKeys, limitsJson:input.limitsJson, active:input.active ?? true }); await this.audit.append(tx,{organizationId:actor.organizationId,actorUserId:actor.userId,action:'SAAS_PLAN_CREATED',subjectType:'SaaSPlan',subjectId:plan.id,afterJson:{key:input.key,limitsJson:input.limitsJson},ip:actor.ip}); return plan; }); }
  async planDetail(id:string){ const plan=await this.repository.getPlan(id); if(!plan) throw new AppError(404,'SAAS_PLAN_NOT_FOUND','SaaS plan not found.'); return plan; }
  async updatePlan(actor:{userId:string;organizationId:string;ip:string|null}, id:string, input:any){ const plan=await this.repository.getPlan(id); if(!plan) throw new AppError(404,'SAAS_PLAN_NOT_FOUND','SaaS plan not found.'); return withTransaction(async(tx)=>{ const updated=await this.repository.withDb(tx).updatePlan(tx,id,{...input, updatedAt:new Date()}); await this.audit.append(tx,{organizationId:actor.organizationId,actorUserId:actor.userId,action:'SAAS_PLAN_UPDATED',subjectType:'SaaSPlan',subjectId:id,beforeJson:{key:plan.key},afterJson:input,ip:actor.ip}); return updated; }); }
  async subscriptions(query:any={}){ return this.repository.subscriptions(query); }
  async subscribe(actor:{userId:string;organizationId:string;ip:string|null}, input:any){
    const plan=await this.repository.getActivePlan(input.planId); if(!plan) throw new AppError(404,'SAAS_PLAN_NOT_FOUND','SaaS plan not found.');
    return withTransaction(async(tx)=>{ const subscription=await this.repository.withDb(tx).createSubscription(tx,{organizationId:input.organizationId,planId:input.planId,status:input.status,startsAt:new Date(input.startsAt),endsAt:input.endsAt?new Date(input.endsAt):null}); const moduleKeys=Array.isArray(plan.moduleKeys)?plan.moduleKeys:[]; await this.repository.withDb(tx).createSubscriptionFeatures(tx,moduleKeys.map((key:string)=>({organizationId:input.organizationId,subscriptionId:subscription.id,featureKey:key,enabled:true,limitJson:plan.limitsJson as never}))); await this.audit.append(tx,{organizationId:input.organizationId,actorUserId:actor.userId,action:'SAAS_SUBSCRIPTION_CREATED',subjectType:'SaaSSubscription',subjectId:subscription.id,afterJson:{planId:input.planId,status:input.status},ip:actor.ip}); return subscription; });
  }
  async subscriptionDetail(id:string){ const row=await this.repository.getSubscription(id); if(!row) throw new AppError(404,'SAAS_SUBSCRIPTION_NOT_FOUND','SaaS subscription not found.'); return row; }
  async updateSubscription(actor:{userId:string;organizationId:string;ip:string|null}, id:string, input:any){ const before=await this.repository.getSubscription(id); if(!before) throw new AppError(404,'SAAS_SUBSCRIPTION_NOT_FOUND','SaaS subscription not found.'); return withTransaction(async(tx)=>{ const updated=await this.repository.withDb(tx).updateSubscription(tx,id,{...(input.planId?{planId:input.planId}:{}),...(input.status?{status:input.status}:{}),...(input.startsAt?{startsAt:new Date(input.startsAt)}:{}),...(Object.prototype.hasOwnProperty.call(input,'endsAt')?{endsAt:input.endsAt?new Date(input.endsAt):null}:{})}); await this.audit.append(tx,{organizationId:updated.organizationId,actorUserId:actor.userId,action:'SAAS_SUBSCRIPTION_UPDATED',subjectType:'SaaSSubscription',subjectId:id,beforeJson:{status:before.status,planId:before.planId},afterJson:input,ip:actor.ip}); return updated; }); }
  async usage(query:any){ const p=page(query); const {rows,total}=await this.repository.usageMetrics(query.organizationId,day(query.from),day(query.to,true),p.skip,p.take); return {rows,total,page:p.page,pageSize:p.pageSize}; }
  async usageDetail(id:string){ const row=await this.repository.getUsage(id); if(!row) throw new AppError(404,'SAAS_USAGE_NOT_FOUND','SaaS usage metric not found.'); return row; }
  async collectUsage(actor:{userId:string;organizationId:string;ip:string|null}, input:any){ return withTransaction(async(tx)=>{ const measuredAt=input.measuredAt?new Date(input.measuredAt):new Date(); const metricRows=[{organizationId:input.organizationId,metricKey:'active_users',metricValue:new Prisma.Decimal(input.activeUsers),measuredAt,sourceJson:{source:'PASS_20_PORTAL_SAAS_READINESS'}},{organizationId:input.organizationId,metricKey:'api_calls',metricValue:new Prisma.Decimal(input.apiCalls??0),measuredAt,sourceJson:{source:'PASS_20_PORTAL_SAAS_READINESS'}}]; const storage={organizationId:input.organizationId,bytesUsed:BigInt(input.storageBytes),objectCount:input.objectCount,measuredAt,sourceJson:{source:'PASS_20_PORTAL_SAAS_READINESS'}}; await this.repository.withDb(tx).createUsage(tx,metricRows,storage); await this.audit.append(tx,{organizationId:input.organizationId,actorUserId:actor.userId,action:'SAAS_USAGE_COLLECTED',subjectType:'TenantUsageMetric',subjectId:input.organizationId,afterJson:{activeUsers:input.activeUsers,storageBytes:input.storageBytes,objectCount:input.objectCount},ip:actor.ip}); return {organizationId:input.organizationId,measuredAt,metricRows:metricRows.length,storageBytes:input.storageBytes}; }); }
  async invoices(query:any={}){ return this.repository.invoices(query); }
  async createInvoice(actor:{userId:string;organizationId:string;ip:string|null}, input:any){ return withTransaction(async(tx)=>{ const invoice=await this.repository.withDb(tx).createInvoice(tx,{organizationId:input.organizationId,subscriptionId:input.subscriptionId,invoiceNo:input.invoiceNo,status:'DRAFT',amount:new Prisma.Decimal(input.amount),dueDate:day(input.dueDate)!,memo:input.memo??null}); await this.audit.append(tx,{organizationId:input.organizationId,actorUserId:actor.userId,action:'SAAS_INVOICE_CREATED',subjectType:'SaaSInvoice',subjectId:invoice.id,afterJson:{invoiceNo:input.invoiceNo,amount:input.amount},ip:actor.ip}); return invoice; }); }
  async invoiceDetail(id:string){ const invoice=await this.repository.getInvoice(id); if(!invoice) throw new AppError(404,'SAAS_INVOICE_NOT_FOUND','SaaS invoice not found.'); return invoice; }
  async updateInvoice(actor:{userId:string;organizationId:string;ip:string|null}, id:string, input:any){ const invoice=await this.repository.getInvoice(id); if(!invoice) throw new AppError(404,'SAAS_INVOICE_NOT_FOUND','SaaS invoice not found.'); if(invoice.status==='POSTED') throw new AppError(409,'SAAS_INVOICE_POSTED_IMMUTABLE','Posted SaaS invoices cannot be silently edited.'); return withTransaction(async(tx)=>{ const updated=await this.repository.withDb(tx).updateInvoice(tx,id,{...(input.amount?{amount:new Prisma.Decimal(input.amount)}:{}),...(input.dueDate?{dueDate:day(input.dueDate)!}:{}),...(Object.prototype.hasOwnProperty.call(input,'memo')?{memo:input.memo??null}:{})}); await this.audit.append(tx,{organizationId:updated.organizationId,actorUserId:actor.userId,action:'SAAS_INVOICE_UPDATED',subjectType:'SaaSInvoice',subjectId:id,beforeJson:{status:invoice.status,amount:String(invoice.amount)},afterJson:input,ip:actor.ip}); return updated; }); }
  async postInvoice(actor:{userId:string;organizationId:string;ip:string|null}, id:string, input:any){ const invoice=await this.repository.getInvoice(id); if(!invoice) throw new AppError(404,'SAAS_INVOICE_NOT_FOUND','SaaS invoice not found.'); if(invoice.status==='POSTED') return invoice; if(invoice.status!=='DRAFT') throw new AppError(409,'SAAS_INVOICE_NOT_POSTABLE','Only draft SaaS invoices can be posted.'); const amount=new Prisma.Decimal(input.amount); if(!amount.isPositive()) throw new AppError(400,'SAAS_INVOICE_AMOUNT_INVALID','Invoice amount must be positive.'); return withTransaction(async(tx)=>{ const updated=await this.repository.withDb(tx).postInvoice(tx,id,amount,day(input.dueDate)!,input.memo??null); await this.audit.append(tx,{organizationId:updated.organizationId,actorUserId:actor.userId,action:'SAAS_INVOICE_POSTED',subjectType:'SaaSInvoice',subjectId:id,afterJson:{amount:amount.toString(),dueDate:input.dueDate},ip:actor.ip}); return updated; }); }
}

// PASS_20_SAAS_STORAGE_USAGE_MODEL: tenantStorageUsage is created through SaaSRepository.createUsage.
